### ISSUE TITLE
Persistence-Query does not continue after connection loss and reconnect 

### ISSUE THREAD

**Issue by synox** [akka/akka-persistence-cassandra#107]
Hi, we are having trouble implementing error handling with persistence-query with cassandra. When the connection is lost and later reconnected, it does not receive any more messages. There are no Failures reported/sent to the Actor running the persistence-query.

We use https://github.com/scalaspring/akka-spring-boot to include akka with spring.

- akka version: 2.4.2
- cassandra version: 3.5 (default config) 

How to reproduce: 
 - clone https://github.com/synox/akka-cassandra-bug-demo
 - build the code with maven "mvn clean install"
 - run class `BackendApplication`
 - you should see alternating "persisted: foo" and "received EventEnvelope(40,my-messages,40,foo)" log statements
 - shutdown cassandra
 - wait 5 seconds
 - restart cassandra
 - wait up to 1 min until the save actor is restarted. 
 - you will see "persisted: foo" log statements only. 

Thanks in advance!

**Comment by jypma** [comment]
Could you upgrade to latest akka-persistence-cassandra and try again? There've been some failure fixes I believe.

**Comment by synox** [comment]
Same problem with 

    <dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-persistence-cassandra_2.11</artifactId>
			<version>0.17</version>
    </dependency>
    <dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-persistence-query-experimental_2.11</artifactId>
			<version>2.4.2</version>
    </dependency>


Due to Issue https://github.com/scalaspring/akka-spring-boot/issues/3 i can not upgrade the akka version.

**Comment by patriknw** [comment]
thanks

**Comment by patriknw** [comment]
anyone up for investigating?

**Comment by synox** [comment]
I removed Spring from my demo and upgraded akka. 

Even with version 2.4.7  and 2.4.8 it does still not work! 

	<dependencies>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-slf4j_2.11</artifactId>
			<version>2.4.8</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-cluster_2.11</artifactId>
			<version>2.4.8</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-cluster-tools_2.11</artifactId>
			<version>2.4.8</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-persistence_2.11</artifactId>
			<version>2.4.8</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-persistence-query-experimental_2.11</artifactId>
			<version>2.4.8</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-persistence-cassandra_2.11</artifactId>
			<version>0.17</version>
		</dependency>
		<dependency>
			<groupId>com.datastax.cassandra</groupId>
			<artifactId>cassandra-driver-core</artifactId>
			<version>3.0.1</version>
		</dependency>
	</dependencies>

**Comment by patriknw** [comment]
@synox I have debugged this and have some good news. Your `IncomingMessageListener` is stopped after 30 restart attempts. See your supervision strategy: `OneForOneStrategy(30, Duration.create("2 minutes")`.

If you just remove the `supervisorStrategy` it works, since then it will restart infinitely. However, you should use `BackoffSupervisor` for that actor also, so that it doesn't restart too quickly.

Let me know if I can close this issue.

**Comment by synox** [comment]
@patriknw Thanks for debugging! Yes this resolves the issue! 

@pspiegel fyi
