### ISSUE TITLE
Make read timeouts configurable

### ISSUE THREAD

**Issue by andy-hw-chung** [akka/akka-persistence-cassandra#108]
We are having issues with actors not being able to recover properly due to read timeouts. Our Cassandra cluster is having difficulty keeping up with the requests it is getting. While we can increase the timeouts on the Cassandra cluster, we cannot configure the timeouts on the client side. These can be configured in the default `ConfigSessionProvider` by passing in `SocketOptions` to the cluster builder. Currently, no socket options are passed in and the default values of 12 seconds for read timeouts is being used.

I can pass in a custom session provider in the config which will allow me to provide the socket options, but I feel like the timeouts (and the other socket options) should be configurable. Perhaps adding a section in the config for socket options is in order?

**Comment by patriknw** [comment]
sounds good, it would be great if you can contribute the change with a pull request

**Comment by patriknw** [comment]
this was fixed long time ago
