### ISSUE TITLE
Should CassandraReadJournal#session be internal API?

### ISSUE THREAD

**Issue by ktoso** [akka/akka-persistence-cassandra#111]
`  val session = new CassandraSession(system, writePluginConfig, ec, log, metricsCategory,`

Likely could be internal API?

**Comment by notxcain** [comment]
As an argument for keeping it public it's very handy to implement read side using this session, as it is already initiated and properly tested Cassandra session wrapper. @patriknw WDYT?

**Comment by patriknw** [comment]
In current shape it should not be public, but I agree that it is useful and we should consider making it a proper public api. Then we should also incorporate stuff from corresponding class in Lagom (originally written by me).

**Comment by patriknw** [comment]
@notxcain I have made it public for real, and added nice API for arbitrary queries and updates. Review is welcome: https://github.com/akka/akka-persistence-cassandra/pull/132
