### ISSUE TITLE
Persistence Query - Serialization issue

### ISSUE THREAD

**Issue by kasper-f** [akka/akka-persistence-cassandra#112]
When using persistence query with cassandra as backend it will resolve in multiple errors when serialization debug is turned on for akka: 
```
akka.actor {
    #verify that all messages are serializable //should only be apllied during test
    serialize-messages = on
    #verify that all props are serializable //should only be apllied during test
    serialize-creators = on
}
```

I have tried with java, [kryo](https://github.com/romix/akka-kryo-serialization) and [twitter/chill](https://github.com/twitter/chill) as serializer.  

when using java serializer I get a `NotSerializableException` for `DefaultPreparedStatement`. See [java_stacktrace.txt](https://github.com/akka/akka-persistence-cassandra/files/363275/java_stacktrace.txt) for full stacktrace.  

when using [twitter/chill](https://github.com/twitter/chill) serializer I get a `ConcurrentModificationException` when`akka.persistence.cassandra.query.EventsByTagPublisher$$anonfun$props$` is called. See [twitterchill_stacktrace.txt](https://github.com/akka/akka-persistence-cassandra/files/363274/twitterchill_stacktrace.txt)
 for full stacktrace.  

when using [kryo serializer](https://github.com/romix/akka-kryo-serialization) I get a `com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 1025316592`. See [kryo_stacktrace.txt](https://github.com/akka/akka-persistence-cassandra/files/363276/kryo_stacktrace.txt) for full stacktrace. 

I have created a small sbt project to reproduce the error with the mentioned serializers : 

[project.zip](https://github.com/akka/akka-persistence-cassandra/files/363345/project.zip)

**Comment by ktoso** [comment]
Thanks for reporting.
Just so we're on the same page, `akka.actor.serialize-messages` is not something one should use in normal code, it checks if _ALL_ actor messages sent around can be serialized. Which often is not a requirement if messages stay local, as is with the journal messages.

The solution of this ticket is to make sure we don't check that message type - it won't leak beyond single VM, so it should not need be serializable

**Comment by kasper-f** [comment]
Thanks for the prompt reply.
I am aware that this should only be used during tests. I am in the process of building up a new system and have this setting enabled in our test scope to make sure all our messages can be serialized.

Took me quite some time playing with different serializers before I could narrow down the problem. 

I started using this setting after I encountered problems starting akka is a cluster setup. As my messages contained akka.typed.ActorRef and it can not be serialized with default java serializer I needed to make sure my messages was serializable. 

Looking forward to see a fix ;-)

**Comment by ktoso** [comment]
> Looking forward to see a fix ;-)

You could contribute a fix :-)

**Comment by kasper-f** [comment]
will see what I can do.
Am i correct that I need to update akka.actor.dungeon.Dispatch in akka-actor module with a filter to exclude classes that needs to be tested?

**Comment by ktoso** [comment]
No, dungeon is a dangerous place you don't want to go alone into (hence the
name :-)).

Since the unserializable message is likely passed along in a class that we
control, (and if it's not, we'll want to make it so),
we can make it extend: `akka.actor.NoSerializationVerificationNeeded` which
will disable the check for classes we know don't need to be serializable.

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 14 July 2016 at 13:43:11, Kasper Fock (notifications@github.com) wrote:

will see what I can do.
Am i correct that I need to update akka.actor.dungeon.Dispatch in
akka-actor module with a filter to exclude classes that needs to be tested?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-persistence-cassandra/issues/112#issuecomment-232642155>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAHYk23HXGMBxb8MAG8hMbUtUPBck29Qks5qViDPgaJpZM4JMO7s>
.

**Comment by kasper-f** [comment]
Oh, already made an implementation in Dispatch https://github.com/kasper-f/akka/commit/a83616ffdc620be62d41bae903a8e311a87a9b37

Will try locate the message where DefaultPreparedStatement is used in akka-persistence-cassandra instead as suggested.

**Comment by kasper-f** [comment]
I actually found that the problem was not the `akka.actor.serialize-messages = on` but `akka.actor.serialize-creators = on` causing every Props to be checked 

I have committed a fix for EventsByTag* but the issue is also present in EventsByPersistenceIdPublisher. @ktoso Before applying the fix for that class as well I would like your input on this solution. (https://github.com/kasper-f/akka-persistence-cassandra/commit/da9c687ed67c3feea60d261df5f794d446c285a7)

**Comment by kasper-f** [comment]
I have fully implemented a new solution where I only wrap session and prepared statement in a new class to escape the serialization validation.
I have created a pull request https://github.com/akka/akka-persistence-cassandra/pull/113 
@ktoso please comment and let me know if there is any issues to be solved before this can get accepted.
