### ISSUE TITLE
waht can I do If cassandra host ip is changed?

### ISSUE THREAD

**Issue by jaohaohsuan** [akka/akka-persistence-cassandra#115]
I am using Kubernetes to run Cassandra, if the Cassandra host ip changed because the container crash or migrate to other node, Is it posible to re-config the `cassandra-journal.contact-points` ? 

Any suggestion?

**Comment by patriknw** [comment]
See session-provider in reference.conf
https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/resources/reference.conf

Not sure it will help you. It is only used when establishing the session and after that the cassandra reconnect management is used.

**Comment by ksilin** [comment]
Programmatic config would be great +1

**Comment by jaohaohsuan** [comment]
Fianlly Kubernetes petset save me. I am not going to rely on pod ip instead service name.

**Comment by kasper-f** [comment]
To start cassandra in kubernetes see their example:  https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/README.md
Akka  can then be configured to use the service name as contact point :
```
cassandra-journal.contact-points` = ["cassandra"]
cassandra-snapshot-store.contact-points = ["cassandra"]
```

**Comment by chbatey** [comment]
We leave configuring the contact points to the driver now
