### ISSUE TITLE
Optionally apply event adapters in queries

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#116]
See https://github.com/akka/akka/issues/18050 and https://github.com/akka/akka/issues/21065

Contribution is welcome!

**Comment by note** [comment]
I wonder if it wasn't addressed somehow. I just set up akka-persistence-cassandra together with Persistence Query and adapter's `fromJournal` is actually called. In akka-persistence-cassandra config I have just `event-adapters`, `event-adapter-bindings`,
`.enable-events-by-tag-query`

**Comment by patriknw** [comment]
@note Good catch. It was added here https://github.com/akka/akka-persistence-cassandra/pull/61
