### ISSUE TITLE
Improved error handling if Cassandra node is down

### ISSUE THREAD

**Issue by lukas-phaf** [akka/akka-persistence-cassandra#145]
I get the following errors in Akka when I take down (unplug the network cable) of a node in our Cassandra cluster:

`[INFO] 2016-12-16 14:10:12,457  4847268  - Retrying on request error on same host at consistency QUORUM (initial consistency: QUORUM, retries: 0, exception: {})
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.7.17.18:9042] Timed out waiting for server response
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:766)
	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1267)
        ...`

The Cassandra driver documentation gives the possible reasons for getting an onRequestError: [http://docs.datastax.com/en/developer/java-driver/3.1/manual/retries/](url)

Some timeouts are of course to be expected in this case, but for the specific error I am getting (OperationTimedOutException), it would be better to retry on another host, instead of the same host. I don't think trying on another host would hurt for the other possible reasons.

My suggestion is to change `onRequestError` of the `FixedRetryPolicy` to use `RetryDecision.tryNextHost` instead of `RetryDecision.retry`.

Note that this is also the default implementation in the DefaultRetryPolicy:
`public RetryDecision onRequestError(Statement statement, ConsistencyLevel cl, DriverException e, int nbRetry) {
    return RetryDecision.tryNextHost(cl);
}
`

**Comment by patriknw** [comment]
Sounds like a good suggestion, @lukas-phaf 
Would you like to create a pull request with that change?

**Comment by lukas-phaf** [comment]
Yes, I can try to do that. It will be my first GitHub pull request, so it might take some time.

I would like your input on one thing: I think `onRequestError` should take into account the number of retries, just like `onWriteTimeout`, `onReadTimeout`, etc. Do you agree?

**Comment by lukas-phaf** [comment]
Our legal department is looking at the CLA. I am afraid it will take a while before I can create the pull request.

**Comment by lukas-phaf** [comment]
For pull request, see #147.
