### ISSUE TITLE
Enable compression via config

### ISSUE THREAD

**Issue by haggy** [akka/akka-persistence-cassandra#146]
I have looked through the reference conf and source and I don't see a way to enable compression on the persistence tables.

Create Table: https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraStatements.scala#L28

Is this not implemented? I believe it should be as easy as adding `AND compression = { 'sstable_compression' : '${config.sstable_compression}'` to the table creation script. If you agree than I can PR. Thanks!

**Comment by patriknw** [comment]
Aren't there a lot of settings that can be defined when creating the tables? I don't think its feasible to replicate all such things into the config. The table creation in CassandraStatements should only be seen as convenience for automated testing. For production I would create the tables manually before starting the system the first time.

**Comment by haggy** [comment]
That's an even better idea that I didn't think of :D

**Comment by patriknw** [comment]
ok, closing then
