### ISSUE TITLE
Columns documentation/description?

### ISSUE THREAD

**Issue by bamarek18** [akka/akka-persistence-cassandra#148]
It would be useful if one had documentation for what which column mean.
For example there is `message` and `event`. What is their difference? What is the `ser_id`? `event_manifest`?

It is useful when trying to migrate.

**Comment by patriknw** [comment]
I agree :)

`message` is the serialized PersistentRepr that was used in v0.6 and earlier.
`event` is the serialized application event that is used in v0.7 and later.

To clarify the `ser_id`, `ser_manifest` and `event_manifest`...

The event's serialization manifest is stored in `ser_manifest` and the `PersistentRepr.manifest` is stored in `event_manifest`.
I can see the confusion :) and I guess the naming went bad in one of many refactorings. Can't change column names now.

The two manifests have different purposes.
`ser_manifest` together with `ser_id` is used for the serialization of the event (payload).


`PersistentRepr.manifest` is used by the event adapters (in akka-persistence).

**Comment by bamarek18** [comment]
@patriknw thanks.
So if I need to migrate from pre0.6, what would be the process? Do I just migrate old messages to `message` column, and leave event, ser_id, ser_manifest & event_manifest nulls? Would that work?

**Comment by patriknw** [comment]
@bamarek18 it's the opposite, but that part is backwards compatible so when replaying the events it will first read from the `message` column and only if that is `null` try with the new columns.

**Comment by bamarek18** [comment]
ah, so like this?:
`old_schema.message -> new_schema.message`
`new_schema.event_manifest` --> `how should I get this value?`
other nulls (besides PKs which would be generated)
Or do I need the event manifest? Sorry for dumb question, but what is ` event's serialization manifest` for ?

**Comment by patriknw** [comment]
you can leave `event_manifest` as `null` or `""` (I would guess `""` is the more safe choice)
`event_manifest` is used for event adapters, which you are not using.

**Comment by bamarek18** [comment]
Thank you. And writer_uuid can stay null ?

**Comment by patriknw** [comment]
Use `""` for `writer_uuid`

**Comment by patriknw** [comment]
And document that the auto creation of keyspace and tables is mostly intended as a convenience for development and tests. For production it's better to create the tables before starting the application so that all needed configuration can be specified.
