### ISSUE TITLE
Migration ShardCoordinator errors

### ISSUE THREAD

**Issue by bamarek18** [akka/akka-persistence-cassandra#151]
When migrated as mentioned in a #148 fashion I am getting lots of message ssimiliar to these:

```
akka.cluster.sharding.PersistentShardCoordinator - Persistence failure when replaying events for persistenceId [/sharding/somethingCoordinator]. Last known sequence number [0]
akka.pattern.CircuitBreakerOpenException: Circuit Breaker is open; calls are failing fast
```

Whats recommended approach? I am running in cassandra2 compact mode.

**Comment by patriknw** [comment]
I don't know what is causing that but you can safely remove such events as described in http://doc.akka.io/docs/akka/2.4/scala/cluster-sharding.html#Removal_of_Internal_Cluster_Sharding_Data

**Comment by patriknw** [comment]
@bamarek18 can we close this? With current information I don't know what to do about it.
