### ISSUE TITLE
Support forking in CassandraLauncher

### ISSUE THREAD

**Issue by jroper** [akka/akka-persistence-cassandra#153]
When Cassandra shuts down, if the platform is Windows, it will call `System.exit(0)`:

```java
   // On windows, we need to stop the entire system as prunsrv doesn't have the jsvc hooks
   // We rely on the shutdown hook to drain the node
   if (FBUtilities.isWindows())
       System.exit(0);
```

This means if using the `CassandraLauncher` in tests to start an embedded Cassandra, then on Windows the test process will be abruptly terminated when the tests tear down callbacks are run.  One solution to this would be to fork the Cassandra launcher if running on Windows.

See https://github.com/lagom/lagom/issues/435 for more details.

**Comment by patriknw** [comment]
ouch

**Comment by jroper** [comment]
I'm going to look at implementing this, see https://github.com/lagom/lagom/issues/664 for why. My approach will be to add an option to fork, and to assume that the classloader that launched `CassandraLauncher` is a URL classloader that contains all the necessary jars, and use that to construct the classpath for the forked process.  The approach is not bulletproof, but should work for all practical purposes.

**Comment by patriknw** [comment]
Thanks
