### ISSUE TITLE
Consider logging stacktrace in warnings on replay failure

### ISSUE THREAD

**Issue by ktoso** [akka/akka-persistence-cassandra#159]
It was requested that we log the exception in detail here https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/snapshot/CassandraSnapshotStore.scala#L87

I'm not sure if this is a good idea or not, WDYT @patriknw ?
Ping me for details

**Comment by patriknw** [comment]
`LoggingAdapter` only supports stack trace for `error`. Problems here are most likely to be because of deserialization (and shouldn't be difficult to reproduce in a unit test)

**Comment by ktoso** [comment]
Hm, yeah I forgot we can't add it on warning :<
