### ISSUE TITLE
Allow `eventsByTag` stream to be completed

### ISSUE THREAD

**Issue by briantopping** [akka/akka-persistence-cassandra#160]
To the best I can tell, `eventsByTag` does not have a way to complete the stream because the materialized value is set to `NotUsed` and there is no good way to override it.

My use case for this is with Elasticsearch. Indexes there become corrupted and need to be rebuilt, in which case the persisted ID needs to be reset, indexes cleared and the stream restarted to rebuild them. 

One could imagine issuing their own `currentEventsByTag` call every interval and not re-issuing the call if the indexes need to be rebuilt, but rebuilds are likely to be necessary once in months (possibly once every 1e9 calls), so this seems like a bad pattern in general.

**Comment by johanandren** [comment]
Did you see the docs for `eventsByTag`? https://github.com/akka/akka/blob/9d2bec7f232b628cc087231af75e457072823e61/akka-persistence-query/src/main/scala/akka/persistence/query/scaladsl/EventsByTagQuery.scala

It describes the semantics as exactly this.

Detecting your elastic search indexes being corrupt and stopping the stream could be done using for example a `KillSwitch` stage. http://doc.akka.io/docs/akka/2.4/scala/stream/stream-dynamic.html#unique-kill-switch-scala

**Comment by briantopping** [comment]
Thanks @johanandren, much appreciated. 

It looks like what I misunderstood was the use of adding a stage to an existing graph. I had read the `eventsByTag` documentation a number of times, looked through both open and closed issues and dug pretty deep into the implementation looking for an option to get at the `Source` actor, but what was needed is as you point out w/ `KillSwitch` is I was not properly adding a stage to the graph that was returned, not that the graph in itself was insufficient. I'll close this assuming that works.

Thanks again
