### ISSUE TITLE
push events from Cassandra

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#161]
The queries are based on periodic polling C* for new events. 

One improvement over only using polling is the Akka Cluster PubSub notifications via `cassandra-journal.pubsub-minimum-interval`, but it's still not optimal.

Would be great if it would be able to push events or notifications directly from C* somehow.

There is Change Data Capture (CDC) in Cassandra but it's an extremely low level api so far. Improvement suggestions based on CDC or something else very much welcome.

**Comment by kant111** [comment]
+1

**Comment by notxcain** [comment]
@patriknw As far as I understand guys from Data Mountaineer have implemented Cassandra to Kafka replication using CDC, see http://docs.datamountaineer.com/en/latest/cassandra-cdc.html. They start connector on each node, though.
