### ISSUE TITLE
Is there any documentation or examples using this lib

### ISSUE THREAD

**Issue by ashishsoni** [akka/akka-persistence-cassandra#162]
Is there any documentation or examples using this lib

**Comment by ktoso** [comment]
All you need is here:
- https://github.com/akka/akka-persistence-cassandra

And the library itself is documented here: 
- http://doc.akka.io/docs/akka/current/scala/persistence.html

Please use the mailing lists or chats fo questions like that though, issues are meant for issues / bugs etc
