### ISSUE TITLE
remove the static column 'used'

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#180]
Investigate if we can remove the static column 'used'. The purpose is to mark that a partition has been used, especially when asyncWriteMessages has an AtomicWrite that is larger than the target partition size. It should be reasonable limitation to not allow persistAll with more events than the target partition size.

A lot of things would be simplified without that column, and users seems to still have problems with earlier Cassandra versions (the know bug is supposed to be fixed in Cassandra 2.1.6). It would also be more performant, e.g. the replay of events is making an extra query for each partition to check the 'used'.

A first small improvement could be to remove this line https://github.com/akka/akka-persistence-cassandra/blob/v0.25/src/main/scala/akka/persistence/cassandra/journal/CassandraRecovery.scala#L59
I don't see the reason for it. If there is a row, the partition is obviously in use and the scan should continue?

**Comment by kpbochenek** [comment]
Sounds like a great improvement and simplification,
this column had meaning when there was no 'deleted_to' property so you had to know that in a next partition might be events even though current one was empty.

With 'deleted_to' flag looks like this invariant holds?:
(deleted_to value > given partition) OR (there are events in given partition) OR (there might be events in next partition if deleted_to points to last sequence_nr in partition)

There is only one comment that suggests it might not be valid:
https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L275

But it does look like this is not needed?

**Comment by patriknw** [comment]
I'm pretty sure that we can remove the static column. I have already removed it's usage in the new eventsByPersistenceId (used for replays) query in https://github.com/akka/akka-persistence-cassandra/pull/238

It's also used when finding highest seqNr. We should perhaps look into why finding highest seqNr is needed. Perhaps it's enough to just replay to the end, and use the last seqNr as highest.

**Comment by chbatey** [comment]
@patriknw I think this is optional for 1.0, WDYT? If we do remove it I think we can do it without downtime

**Comment by patriknw** [comment]
Increasing priority of this. Seems like one row for this column is remaining even though all events have been removed.
