### ISSUE TITLE
EventsByTag query drops events after going into LookingForDelayed state

### ISSUE THREAD

**Issue by TrustNoOne** [akka/akka-persistence-cassandra#197]
I have a database containing tags with hundreds of thousands of events. EventsByTag query with no offset (i.e. all events) stopped working properly after the backtracking fix in 0.25. 

[this log](https://pastebin.com/raw/yKndFrW5) shows what's happening when I execute this:
`journal.eventsByTag("epman3", NoOffset).runWith(Sink.ignore)`. `epman3` is a tag I have in my local database (tag2), it has more than 100k events over 3 months.

This is what I think is happening: the query starts reading events normally from the `first-time-bucket` offset

```
...
17:36:15.829 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query for tag [epman3] from [20170212] [c88d0000-278b-11e6-8080-808080808080 (2016-06-01 00:00:00)] limit [500]
17:36:15.831 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query chunk done for tag [epman3], timBucket [20170212], count [0] of [0]
17:36:15.832 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query for tag [epman3] from [20170213] [c88d0000-278b-11e6-8080-808080808080 (2016-06-01 00:00:00)] limit [500]
17:36:17.094 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query chunk done for tag [epman3], timBucket [20170213], count [254] of [254]
17:36:17.094 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query for tag [epman3] from [20170214] [86539310-f248-11e6-b7ea-2d28b749ed03 (2017-02-13 23:59:58)] limit [500]
17:36:17.696 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query chunk done for tag [epman3], timBucket [20170214], count [500] of [500]
...
```

Then, after [`min(20s, delayed-event-timeout/2)`](https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/query/EventsByTagPublisher.scala#L180) seconds it goes into LookingForDelayed state.

```
17:36:27.435 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query for tag [epman3] from [20170301] [52052ba0-fe78-11e6-868a-2d28b749ed03 (2017-03-01 12:12:20)] limit [500]
17:36:27.555 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query chunk done for tag [epman3], timBucket [20170301], count [500] of [500]
17:36:27.796 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - backtracking delayed query for tag [epman3] from [20170301] [26534970-fe9a-11e6-8080-808080808080 (2017-03-01 16:14:30)] limit [500]
17:36:27.800 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - backtracking delayed query chunk done for tag [epman3], timBucket [20170301], count [0] of [1]
17:36:27.800 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - backtracking delayed query for tag [epman3] from [20170302] [3834ec70-fe9a-11e6-868a-2d28b749ed03 (2017-03-01 16:15:00)] limit [500]
17:36:27.802 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - backtracking delayed query chunk done for tag [epman3], timBucket [20170302], count [0] of [0]
17:36:27.802 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - backtracking delayed query for tag [epman3] from [20170303] [3834ec70-fe9a-11e6-868a-2d28b749ed03 (2017-03-01 16:15:00)] limit [500]
17:36:27.803 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - backtracking delayed query chunk done for tag [epman3], timBucket [20170303], count [0] of [0]
```

the backtracking query proceeds until the current date, then the normal query starts again skipping everything between the current bucket at the time of the delayed query and today

```
:36:27.914 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - backtracking delayed query for tag [epman3] from [20170420] [3834ec70-fe9a-11e6-868a-2d28b749ed03 (2017-03-01 16:15:00)] limit [500]
17:36:27.916 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - backtracking delayed query chunk done for tag [epman3], timBucket [20170420], count [0] of [0]
17:36:30.795 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query for tag [epman3] from [20170420] [3834ec70-fe9a-11e6-868a-2d28b749ed03 (2017-03-01 16:15:00)] limit [500]
17:36:30.797 DEBUG akka.persistence.cassandra.query.EventsByTagPublisher - query chunk done for tag [epman3], timBucket [20170420], count [0] of [0]
```

Furthermore, if the (broken?) backtracking query for `LookingForDelayed` takes more than `delayed-event-timeout/2`, it loops indefinitely without ever leaving the backtracking state.

I haven't looked too deeply into this, but shouldn't the backtracking query stop at `highestOffset`? It seems like there's something broken there, something like it's not `timeForReplay` when `backtracking && currOffset == highestOffset` or similar

**Comment by rcavalcanti** [comment]
Hi @TrustNoOne,

There were some hidden bugs that came to the surface on 0.25. Not sure if you are hitting it though. 
Release 0.25.1 fixed them, so you should consider updating.

Current release is 0.26, so it's worth give it a try.

**Comment by TrustNoOne** [comment]
This seems to work, I'm not sure of other implications of that check, let me know what you think

https://github.com/akka/akka-persistence-cassandra/compare/master...TrustNoOne:197-delayed-eventsbytag-fix?expand=1

**Comment by TrustNoOne** [comment]
@rcavalcanti I'm on 0.51 shouldn't it contain everything in 0.25.1 or is it lagging behind? I haven't checked yet

**Comment by patriknw** [comment]
Thanks for reporting. So you still see the problem with 0.26? Can you share the same logs with 0.26?

Do you have a reproducer that can be shared? It would be best if we can add a reproducer to the test at https://github.com/akka/akka-persistence-cassandra/blob/master/src/test/scala/akka/persistence/cassandra/query/EventsByTagSpec.scala#L815

**Comment by patriknw** [comment]
0.51 == 0.26
0.50 == 0.25.1

**Comment by TrustNoOne** [comment]
Well then I guess 0.26 would behave the same, I'll try anyway in a minute.
at the moment I can only reproduce this by populating the database with a month of data and lots of events, I'll take a look at the test and see if I can simulate it somehow later

**Comment by patriknw** [comment]
0.51 or 0.26 doesn't matter, it's 0.25 that is broken

**Comment by TrustNoOne** [comment]
Ok then apparently this is another issue. I haven't looked yet at what was solved in 0.26/51 anyway. I'm now looking at the test, I guess I should look for the example that tests the 'LookingForDelayed' phase

**Comment by TrustNoOne** [comment]
I added a test that reproduces the issue on my laptop. It's something strictly depending on the query execution speed so it could maybe not fail on very fast hardware. I'm not sure this is the best way to reproduce it, @patriknw I'll wait for your insights about this matter. I think the problem is clearer now, if we start an EventsByTag query N days ago with N big enough, the query skips everything between the current offset at the time the delayed event backtracking kicks in and now.

The test I added fails on master and passes with my modification of EventsByTagPublisher on my laptop.

I can open a pull request if you think it's worth it but somehow I think this could be solved in a better way, what do you think? Something like looking for delayed only when we have "never-seen-before persistenceIds" in the tag stream. A quick fix could be the best choice in the short term anyway.

Here's the fix/test: https://github.com/akka/akka-persistence-cassandra/compare/master...TrustNoOne:197-delayed-eventsbytag-fix?expand=1

**Comment by TrustNoOne** [comment]
@patriknw do you have a time frame for the next release? I'm not in a big rush, it's just for information

**Comment by patriknw** [comment]
I can probably release later this week. I'm thinking that @jroper might want to complete https://github.com/akka/akka-persistence-cassandra/pull/196 first.
