### ISSUE TITLE
Memory Issues processing large numbers of events

### ISSUE THREAD

**Issue by richard-hunt** [akka/akka-persistence-cassandra#210]
Hi,

Logging this here on advice from the Lagom User Group.   I have implemented a Lagom service which is using akka-persistence-cassandra 0.26 under the covers for persistence.

During normal operation, everything works well, but if for any reason a large number of events have queued up for processing I'm seeing massive JVM memory spikes, with throughput dropping to almost zero and GC at 100% CPU.  A heap dump revealed 3 instances of akka.persistence.cassandra.query.EventsByTagPublisher consuming 500Mb of heap space each, each with a Vector containing around 68000 event instances.

I've had a look at the EventsByTagPublisher source and it seems the Vector is a buffer of events loaded from Cassandra - the maximum size of this buffer should be controlled by cassandra-query-journal.max-buffer-size, which defaults to 500.  I'm at a bit of a loss to explain how the buffer sizes are growing so big - has anyone seen anything like this before?

I can provide a heap dump if it would be useful.

Thanks,
Richard

**Comment by patriknw** [comment]
Thanks for reporting, we can continue the discussion here if you like.

For reference, here is the other discussion: https://groups.google.com/d/msg/lagom-framework/rleQk4GVC-4/j4edmkjgBAAJ

cc @jroper

**Comment by richard-hunt** [comment]
Thanks Patrik,
Will turn on akka debug logging when I get into work tomorrow and see if I can provide any more insightful information.  I'll also try to see if upgrading to the latest version of akka-persistence-cassandra makes any difference.

**Comment by patriknw** [comment]
The log is useful. Obviously something is wrong. It would be good with full log (zip and attach here).
You can pick one tag if you like `grep "SaleEvent1"`.

I'll try to create a test case for what I think is the scenario.

**Comment by patriknw** [comment]
By the way, please use the latest version, i.e. `0.28`. I think that was `0.27`.

**Comment by patriknw** [comment]
I have a reproducer and understand the problem. The fix is not as simple as to limit the fetch to remaining buffer capacity, because the missing event might be further back than the full buffer size (events from other persistenceId that are already consumed are also fetched). I think I know a solution that should work and still not use more memory than the buffer size.

**Comment by richard-hunt** [comment]
That's good news, thanks for your help Patrik.

**Comment by patriknw** [comment]
An update, I have been very busy with other things, but I'll get back to fixing this (probably on Friday)
