### ISSUE TITLE
possibility to disable materialized view

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#22]
configuration property to skip materialized view in case eventsByTag query is not needed

**Comment by magro** [comment]
What do you think about setting skipped to true by default? I'd assume that it should work if one decides later to use it and enables materialized views / eventsByTag support for an existing event log.

**Comment by patriknw** [comment]
I'd rather have things working out of the box, and make it possible to disable as tuning. I'll see if I can make creation of the materialized view lazy so it's not even created until some events are tagged.

**Comment by magro** [comment]
Ok, sounds good.
