### ISSUE TITLE
Set table default_time_to_live from the journal config

### ISSUE THREAD

**Issue by barambani** [akka/akka-persistence-cassandra#220]
Hi, are there any chances to add the table default_time_to_live property to the journal config ?

**Comment by ktoso** [comment]
Setting a TTL on a table just like that is not really in the spirit of event sourcing and could lead to dropping events that you have not compacted into a snapshot though - what's your use case? Are you sure event sourcing is the right tool for what you're building if you find yourself wanting to use table wide TTLs?

**Comment by barambani** [comment]
I see your point. Consider having some column families that don't contain your source of truth but some aggregates that are needed only for a limited time window (think to a sport event or a car race) and after the end of this window are not needed anymore. They can always be recreated if needed for analysis or reporting (and very rarely are). Those tables are consuming space. A way to expire them would be to use this default ttl together with the Time Window compaction strategy. In this case handling the history of those aggregates with event sourcing still makes sense during the time window when they are used, but then they can be expired without worrying too much about their consistency.
I hope I could express the problem clearly enough. Anyway if you think this option will never be interesting for the project, we can close this issue. There is a work-around that's setting the property using CQL. Thanks for the help.

**Comment by patriknw** [comment]
Note that the auto-creation of the tables is only intended as a convenience for dev/test. We will not mirror all properties. For production (and real testing) you should instead create the tables with CQL and then you have full access to all Cassandra features.
