### ISSUE TITLE
Add support for Time Window Compaction Strategy to the journal configuration

### ISSUE THREAD

**Issue by barambani** [akka/akka-persistence-cassandra#221]
Hi, is there any interest in supporting the Time Window Compaction Strategy in the journal configuration ? It can help improving disk usage and read performances under heavy loads. More details about the strategy here

https://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsConfigureCompaction.html

https://docs.datastax.com/en/cassandra/3.0/cassandra/dml/dmlHowDataMaintain.html

Thanks.

**Comment by chbatey** [comment]
Hi @barambani the latest version now supports TWCS, thanks for reporting this.
