### ISSUE TITLE
Enabled authentication does not support credentials update

### ISSUE THREAD

**Issue by ayurchuk** [akka/akka-persistence-cassandra#227]
We are using `cassandra-journal` with enabled `authentication` in our application.
Also during Cassandra Cluster initialization, we are updating its credentials.
Therefore scenario when an application cannot connect to Cassandra at the beginning but later can is ok for us. The problem is that application keeps saying that new credentials are not valid.

Is there a way or property to avoid this while using `akka-persistence-cassandra`?
We are using akka-persistence-cassandra: v0.29
```
c.d.d.c.Cluster -  - Authentication error during reconnection to ..., scheduling retry in 4000 milliseconds
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host ...: Username and/or password are incorrect
```

**Comment by chbatey** [comment]
We now just expose the drivers config for doing this
