### ISSUE TITLE
Allow to select tag index based on tag prefix

### ISSUE THREAD

**Issue by notxcain** [akka/akka-persistence-cassandra#231]
Imagine a multitenant payment processing system where each `Transaction` is identified by a pair `(TenantId, ExternalTransactionId)`. 
1. To drive business processes I need to be able to process all `TransactionEvent` internally, tagged with `s"TransactionAll$n"` where `n` is partition number.
2. Also I need to expose events to tenants, i.e. be able to read all events tagged with `s"TransactionTenant$tenantId"`.

What if we allow to specify tag index based on its prefix, e.g. introduce new config
```hocon
cassandra-journal {
  use-tag-prefixes = true
  tag-prefixes {
    "TransactionTenant" = 1
    "TransactionAll" = 2
  }
}
```

WDYT? If it seems ok, I would work on it.

**Comment by chbatey** [comment]
Closing this as it was done and i don't think we need it in the new impl as we can have any number of tags
