### ISSUE TITLE
EventsByTagPublisher skips timebucket when there's no demand from upstream and buffer is relatively small

### ISSUE THREAD

**Issue by Leammas** [akka/akka-persistence-cassandra#237]
I experience weird issue with `eventsByTag` query. At some point underlying ActorPublisher has 0 demand from upstream, though I use Sink.ignore. Buffer starts to grow and, eventually, the actor queries cassandra not for all events from a timebucket but with a `limit = maxBufferSize - buf.size`. The query completes, `mightBeMore is false`, the actor shifts to the next timebucket skipping events which it has not even queried. Here it comes a huge hole in the eventstream. The actor sees the event of some persistenceId it has seen before but sequence number is wrong (because there were skipped events of this persistenceId among skipped in previous timebucket). Next it tries to backtrack but it seems impossible to cover so large gap so finally it fails with deadline overdue and IllegalStateException.
Unfortunately I have been able to create a minimal reproducible case only [with a piece of my actual database with 1772 events](https://github.com/Leammas/akka-persistence-cassandra/commit/7e0a459ff99fe0cc5b5d2c7f11e8ccc7f23345cb). Run `sbt 'testOnly *EventsByTagStrictBySeqZeroDemandIssueSpec*'` for this test.
I've made some explicit logging where you can see how buffer grows and skips the events.
The log is in the attachment.
[log.log](https://github.com/akka/akka-persistence-cassandra/files/1344587/log.log)
The error-source query is 

```
backtracking missing query for tag [T5] from [20170914] [0bae9020-9873-11e7-930e-613c3577570c (2017-09-13 11:02:34)] limit [48]
```

It does not queried timebucket `20170914` again but there's not 48 but 700 events. So 652 were skipped.

**Comment by patriknw** [comment]
Thanks for an excellent issue report. The new test doesn't fail for me, but I'll look at your log.

**Comment by patriknw** [comment]
I have found the issue and have a fix in progress.

**Comment by Leammas** [comment]
Great! Thanks a lot.

**Comment by stijndehaes** [comment]
@Leammas Good catch finding this out. Having an issue with a lagom micro service where replaying a lot of events in a read side processor also skips events. I am guessing that this is the same underlying issue you have.

**Comment by patriknw** [comment]
@Leammas 0.57 has been released

**Comment by Leammas** [comment]
The problem we had has gone. Thank you!

**Comment by stijndehaes** [comment]
I can confirm that the problem on my side is gone as well!

**Comment by patriknw** [comment]
thanks for confirming

**Comment by TimMoore** [comment]
It looks like this issue also affects the Akka 2.4-compatible branch (v0.29). @patriknw do you plan to backport? I think it would be good to make this fix available to Lagom 1.3. If you'd like I can send a pull request against the `release-2.4` branch with a cherry-pick of your changes from #240 (unless you'd prefer to handle it yourself). We'd then need a v0.30 release to consume.

**Comment by patriknw** [comment]
@TimMoore I can backport this and release 0.30

**Comment by patriknw** [comment]
@TimMoore 0.30 released with this included

**Comment by TimMoore** [comment]
Fantastic, thanks @patriknw!
