### ISSUE TITLE
Share cassandra Cluster object between read/write and snapshot by default

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#242]
We currently create 3 separate `Cluster` objects from the driver. These all maintain their own connections/thread pools.

**Comment by patriknw** [comment]
It's related to how things are configured, which is mess. See https://github.com/akka/akka-persistence-cassandra/issues/81

journal (write), snapshots, query are separate, but then there is also a relation between journal and query for the replays.

**Comment by chbatey** [comment]
Depends on https://github.com/akka/akka-persistence-cassandra/issues/491
