### ISSUE TITLE
Document eventsByTag semantics (ordering) more

### ISSUE THREAD

**Issue by ktoso** [akka/akka-persistence-cassandra#248]
We should recommend:

"We strongly recommend enabling delayed-event-timeout (see reference.conf of the cassandra plugin) when you care about retrieving all events." or similar.

More good info in here https://groups.google.com/forum/#!topic/akka-user/TH8hL-A8I4k 

It also depends what semantics we'll offer when we'd move off from materialized views https://github.com/akka/akka-persistence-cassandra/issues/247

**Comment by peterlgh7** [comment]
I strongly agree with this. After reading reference.conf, I was under the impression that, with delayed-event-timeout disabled, I would lose delivery order guarantees, but would still get all events eventually. Possibility of skipped events should be clearly documented, as it can be unacceptable for some projects(my company's included).

**Comment by chbatey** [comment]
I've added a `EventsByTag.md` for the new version so closing this.
