### ISSUE TITLE
`currentEventsByPersistenceId` always returns an empty List

### ISSUE THREAD

**Issue by erip** [akka/akka-persistence-cassandra#252]
Sorry for a mishmash of tools, but I'm using Lagom with a Cassandra backend.

I've described the issue on StackOverflow [here](https://stackoverflow.com/questions/46864054/how-do-i-read-all-events-of-a-certain-type-from-a-lagom-persistententitys-read).

**Comment by erip** [comment]
Possibly because `readJournal.currentPersistentIds().runWith(Sink.seq[String])` is always `Nil`.

**Comment by chbatey** [comment]
Hi @erip I'd suggest raising this with lagom as this `currentEventsByPersistenceId` and `currentPersitenceIds` work when using this plugin directly.

**Comment by erip** [comment]
@chbatey I think it might be on lagomlagom#1067
