### ISSUE TITLE
Synchronous EventByTag consistency option

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#259]
With the new eventsByTag implementation we could offer an option for a `persist` to only complete once the tag write is complete. Would hinder performance.

Only do this is there is user demand as it is at odds with our desire to batch cassandra writes for throughput.

**Comment by calvinlfer** [comment]
Hey @chbatey, curious to know what's the impact if there's a system failure before the tag write is complete (in batched mode). Are we able to recover from this?

**Comment by chbatey** [comment]
For the new implementation that isn't in master yet we plan to fix this when the persistent actor is recovering. The tag writer will, best effort, keep track of how far it gets and the recover will complete any tag writes that were missing potenetially writing the tags again but this doesn't matter as they are upserts.

**Comment by calvinlfer** [comment]
Nice 😀 
Thanks!

**Comment by ksmolder** [comment]
Do I understand correctly that currently the Future of the `asyncWriteMessages` method is filled in when the events are written in the messages table but that updating the tag view can still take some time (seconds?) to complete?

**Comment by chbatey** [comment]
Yep that's right @ksmolder, they're async (as was the materialized view impl)

**Comment by chbatey** [comment]
This would also be useful to help with back pressure when the database is overloaded.

The batching to the tag_views makes the writes more efficient but detaching them from the write to the messages table means that if they slow down and the writes to the messages table don't then use code won't get any indication the database is overloaded.

This is more likely to happen if there are many tags for a single event meaning that the write to the tags tables is more expensive than to the messages table.

For these cases I think we should support setting batch size to 1 for the tag views that also makes the write synchronous with the user's persist call

**Comment by chbatey** [comment]
Thinking about this some more we don't need to set the batch size to 1. Messages with the same tag from different persistence id can still be batched.

If we make the tag write respond and be part of the persist then setting the flush interval to 0 would mean that batching would still happen when events are batched while there is a write to the tag_view table outstanding

**Comment by patriknw** [comment]
sounds good
