### ISSUE TITLE
Eventual consistency for delayed events 

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#263]
The old impl had two options that are no longer supported but could both be added.

**Eventual consistency**: Don't read recent events so that events are more likely to come out in timeuuid order. This is still a valid feature and needs doing for the new implementation.

**Delayed**: If every event is tagged then use the sequence numbers to delay delivery of events if a sequence nr is missing as well as periodically going back to look for new events. 

The new implementation guarantees this all the time by adding a new sequence nr per tag per persistenceId so detect gaps all the time. However if an event is delayed and an eventByTag query has already gone past that offset it won't go back and search for it until another event comes. This could be an issue for very in frequent event publishes when different nodes have clocks out of sync. It is likely a small eventual consistency delay can fix this so this feature won't be implemented unless their is user demand.

**Comment by ktoso** [comment]
This is part of the 0.80+ series changes right @chbatey ?

**Comment by ktoso** [comment]
(Assigning milestone would be nice :-))

**Comment by chbatey** [comment]
Not sure why this is closed

**Comment by ktoso** [comment]
Ah, good, that explains a lot then :)

**Comment by Reeebuuk** [comment]
Thx @chbatey for linking these issues. So nobody is using the resuming with eventsByTag?
Clients usually replay the whole journal during boot or?

Resume implementation seemed like a very reasonable and usual thing to do. Is there an ETA for this being implemented/resolved?

**Comment by chbatey** [comment]
HI @Reeebuuk this will be planned for the next version

**Comment by Reeebuuk** [comment]
Great news, thanks @chbatey!
