### ISSUE TITLE
support old format in first-time-bucket config

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#305]
first-time-bucket = "20160225"
IllegalArgumentException: Invalid first-time-bucket format. Use: yyyyMMdd'T'HH:mm

I thought we fixed this, but seems not.

**Comment by chbatey** [comment]
Were you using Day as bucket size? We do have a test for this: https://github.com/akka/akka-persistence-cassandra/blob/bf6bcbfa5d5616a285872ff605430c5b18ea289c/core/src/test/scala/akka/persistence/cassandra/CassandraReadJournalConfigSpec.scala#L25

**Comment by patriknw** [comment]
It was when trying to use 0.80 with lagom 1.4 with old config. I'll forward the email to you. No change to bucket size, since that config was not known previously.

**Comment by chbatey** [comment]
Gotcha, so the old format only works if you use Day and we made Hour the default. Do we want to allow the old format for other bucket sizes? Might force users to think about bucket size when migrating.

**Comment by patriknw** [comment]
Ah, perhaps we could detect this situation and throw an explaining exception?
