### ISSUE TITLE
upgrade to sbt 1.1

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#314]

**Comment by jiminhsieh** [comment]
This issue is blocked by https://github.com/jrudolph/sbt-optimizer, sbt-optimizer doesn't release for sbt 1.x. We need to wait for one of https://github.com/jrudolph/sbt-optimizer/pull/16 and https://github.com/jrudolph/sbt-optimizer/pull/15 merged.

**Comment by chbatey** [comment]
We can remove sbt-optimizer in the mean time. It was there to speed up the build at one point

**Comment by chbatey** [comment]
i'll do this as i am upgrading some other plugins

**Comment by jiminhsieh** [comment]
Sorry, I have been busy recently. I did try locally, but I didn't have enough time to finish.

**Comment by ennru** [comment]
Current sbt version is 1.2.6.
Closing.
