### ISSUE TITLE
TagWriter fails when actor is restarted before tag progress is written

### ISSUE THREAD

**Issue by TrustNoOne** [akka/akka-persistence-cassandra#319]
I am trying to reproduce a bug I have in a test. This is what I think happens:
- some tagged events are written and then the actor is stopped
- the actor is restarted but the [tag progress lookup](https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/CassandraRecovery.scala#L43) doesn't see the progress because [it has not yet been written](https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/TagWriter.scala#L171)

In my test it crashes [here](https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/TagWriter.scala#L108) most of the times, while in a [simplified reproducer I made](https://github.com/TrustNoOne/akka-persistence-bug-reproducer/blob/master/src/main/scala/bug/BugReproducer.scala) it seems to crash [here](https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/TagWriter.scala#L292)

I am not 100% sure of what's happening yet, maybe this can give you some insight on the matter. Here are [some logs from the reproducer](https://pastebin.com/gtVgrY7m)

**Comment by chbatey** [comment]
Thanks for the detail. It is expected that we'll miss some writes from a shutdown and recover them on restart from the events table but something must be wrong with that process. I'll take a look

**Comment by chbatey** [comment]
When running your reproducer I had it crash in the same place as your test rather than the second place.

That is a sanity check to make sure that CassandraJournal sends messages in sequence nr order (mainly put in to make sure the assumptions about akka persistence were correct). However in this case it isn't out of order it is receiving the same event from recovery than directly from the persistent actor.

A quick fix the tag writer could drop the buffered events as well as all subsequent sequence numbers as recovery will be handling them.

Or probably better we could have a better protocol for recovery i.e. not just send a tag write progress but explicitly say, recovery is happening now and this is the tag write progress its based off so drop any buffered events that are in the future.

**Comment by TrustNoOne** [comment]
I guess that would work well. What happens when recovery is started with an outdated write progress? Tagged events are written again I guess?

**Comment by chbatey** [comment]
Yep, and the primary key is deterministic so it will upsert rather than duplicate events. 

I went with the second option while i'll raise a PR for soon. We can cut a release if it blocks you @TrustNoOne or if you can work off the snapshot we can see if you find any other issues?

**Comment by TrustNoOne** [comment]
I'm more than happy to test it off the snapshot, is it published on a public repo?

**Comment by chbatey** [comment]
@TrustNoOne I've raised https://github.com/akka/akka-persistence-cassandra/pull/322 and adapted your reproducer to a test called EventsByTagRestartSpec.scala which restarts an actor many times.

**Comment by TrustNoOne** [comment]
I am trying to build it locally to test it but it can't find org.boris:pecoff4j:0.0.2.1, any idea how I could test it?

**Comment by chbatey** [comment]
That's odd, I don't see it in `dependencyGraph` and I don't have it in my local cache.

**Comment by TrustNoOne** [comment]
It was due to an old version of coursier I was using, it was ignoring the exclusion in [sbt-whitesource](https://github.com/lightbend/sbt-whitesource/blob/master/build.sbt). I upgraded coursier to 1.0.1 and it works now. I'll report back after testing it tomorrow, sorry for the unrelated bug ;)

**Comment by TrustNoOne** [comment]
done, everything looks good 👍

**Comment by chbatey** [comment]
Thanks for validating, will cut a release today or tomorrow.

**Comment by chbatey** [comment]
FYI this is in 0.82
