### ISSUE TITLE
Delete persistenceId 

### ISSUE THREAD

**Issue by ikr0m** [akka/akka-persistence-cassandra#329]
I can delete events and snapshots. It's nice. 
I create persistenceIds dynamically and it leads many persistenceIds. Many of them are not used after some period (because they are already used and not necessary anymore) and I want to delete those persistenceIds. 
Looks like it's not possible currently to delete persistenceIds. So I propose like this:
1. Delete persistenceIds by persistenceId
2. Purge persistenceIds if they don't have events (`sequence_nr` and `event` are null in cassandra table).

I'm asking it here, but it might require changes in https://github.com/akka/akka (akka-persistence) too

**Comment by chbatey** [comment]
Offering a clean up API would be possible. We started to do that in `CassandraDeletion` but didn't make it public. It could either be an official API provided by Akka that we implement or just a custom one for this plugin. Would you like to work on that?
