### ISSUE TITLE
Make schema statements more accessible

### ISSUE THREAD

**Issue by masih** [akka/akka-persistence-cassandra#330]
Considering: 
- it is recommended, [by the framework itself](https://github.com/akka/akka-persistence-cassandra/blob/v0.83/core/src/main/resources/reference.conf#L48-L51), to create the schemas manually, and
- the lack consistency guarantee in Cassandra schema create/alter/delete statements

would it be possible to make the statements such as [this](https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/CassandraStatements.scala) more accessible so that they can be re-used in external schema management tools?

Thanks

**Comment by chbatey** [comment]
Good idea

**Comment by TimMoore** [comment]
As part of this, it would also be handy to create a utility to print out the schema statements without executing them.

**Comment by ktoso** [comment]
> print out the schema statements without executing them.

Yeah great idea. Maybe even do so when plugin starts and the tables not yet there?
With auto create still print them but also a warning to not use auto create?

**Comment by TimMoore** [comment]
> Maybe even do so when plugin starts and the tables not yet there?

That's a good idea, too, but I was thinking of a CQL script generator that could be run separately from the app with deployment automation tooling. So, not logging, but just output the CQL to standard output so you can pipe it to `cqlsh` for example.

> With auto create still print them but also a warning to not use auto create?

Not sure. It's fine for development and testing, and we wouldn't want to be too noisy in those environments.

**Comment by ktoso** [comment]
For dev and testing I'd think we want to move to enabling this mode perhaps... @chbatey likely has opinion here.

But the println we want anyway so let's prep those I think.
Could be a small app, though a bit weird to me... no strong opinion on it though.

**Comment by patriknw** [comment]
Sounds good. Probably best to provide it as a Seq[String] and then it can be piped to whatever. Perhaps keep the keyspace and table statements separate.
Note that it must be running with the right ActorSystem since some is taken from config.

Later I'd also like to include the statements in the documentation.

**Comment by chbatey** [comment]
:+1: if we can run this and put it in docs

**Comment by patriknw** [comment]
I'll do this now (tomorrow)
