### ISSUE TITLE
batch size when writing to tag_views table way ahead of the default 50KB limit. 

### ISSUE THREAD

**Issue by sreeraaman** [akka/akka-persistence-cassandra#339]
Hello Everybody,

We have an event sourced application that writes to Cassandra via Akka Persistence Cassandra version 0.83.

While ingesting data from more than one node via scala kafka client akka actor (https://github.com/cakesolutions/scala-kafka-client), we observed that cassandra throws the following error:

**ERROR 07:36:42 Batch of prepared statements for [akka.tag_views] is of size 9099049, exceeding specified threshold of 655360 by 8443689. (see batch_size_fail_threshold_in_kb)**

We have a 3 Node cassandra cluster running on Mesosphere DC/OS 1.11.0 each with 24G physical RAM, 12 G Heap, 2.4 G for New Gen, using CMS for GC.

We are running on Cassandra 3.0.16. We observed the same behaviour even on Datastax Cassandra 5.1. The batch_size_fail_threshold_in_kb is set at 640KB for now (default with datastax)

The same application runs on a single node without any issues.

Can somebody provide us with some insights into what and where exactly we are missing?

Thanks in advance.
Best regards
Sriraman.

**Comment by chbatey** [comment]
It is configurable so you can adjust it based on sthe size of your events. See https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/resources/reference.conf#L165

Questions are better off on https://discuss.lightbend.com/c/akka/ with the persistence tag rather than raising issues.
