### ISSUE TITLE
Retrieve event occurrence time via currentEventsByPersistenceId

### ISSUE THREAD

**Issue by sreeraaman** [akka/akka-persistence-cassandra#340]
Hello Everybody,

We wanted to show an audit trail showing the list of events, their sequence numbers and the occurrence time for each persisted entity via currentEventsByPersistenceId query.

The query is as follows:
`
val journal = PersistenceQuery(context.system).
        readJournalFor[CassandraReadJournal](CassandraReadJournal.Identifier)
      journal.currentEventsByPersistenceId(s"UserEntity-$persistenceId",0, Long.MaxValue)
.runForeach { e =>
          println(s"${e.persistenceId}\t${e.event.getClass.getSimpleName}\t${e.sequenceNr}\t${e.offset}")

}`

returns the following output:

UserEntity-74a0b178-0298-4cf3-8d7a-0eabc905389c UserPasswordResetted    9       Sequence(9)

The EventEnvelope's offset attribute returns a sequence rather than a timeuuid which is what we want to extract the event occurrence time.

Are we missing anything here?

best regards
Sriraman.

**Comment by chbatey** [comment]
Hi @sreeraaman the TimeUUID offset is only used for the eventsByTag query as there is no natural sequence number. I think your only option would be to include a time in the event if you want them as part of your processing on the read side.
