### ISSUE TITLE
This repository is not searchable without "fork: true" option

### ISSUE THREAD

**Issue by jmyeong** [akka/akka-persistence-cassandra#345]
When I typed "akka-persistence-cassandra" in search form of github, this project doesn't show because this project was forked from original project. but the original project(https://github.com/krasserm/akka-persistence-cassandra) is not maintained anymore. 

I think, this project(https://github.com/akka/akka-persistence-cassandra) will be better to be displayed first, when we search with "akka persistence cassandra". Is it possible to cut fork relationship from original one or is there another way to make this project to be searchable easily?

**Comment by chbatey** [comment]
Unfortunately the original owner doesn't want us to make this the main one. We could consider detatching this at some point.

**Comment by dwijnand** [comment]
It's possible to request that the repo be made a standalone repository:

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

(from https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork)

I was able to follow this process to detach a fork with the following message:

> Hi GitHub Support!
> 
> As detailed in https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork, please could you detach https://github.com/sbt/sbt-launcher-package from https://github.com/paulp/sbt-extras, turning it into a standalone repository. Note I co-maintain both, but they're distinct entities at this point.
> 
> Also, any fork of sbt/sbt-launcher-package should move with sbt/sbt-launcher-package into a new network, rather than remain in the current network.
> 
> Thank you,
> Dale

**Comment by ennru** [comment]
Fixed.
It is now detached from the original GitHub repository.
