### ISSUE TITLE
No way of changing load balancing policy

### ISSUE THREAD

**Issue by asenovm** [akka/akka-persistence-cassandra#352]
Hi,

I'm trying to use RoundRobin load balancing policy, but I'm popping into the following issues:
 - Not setting local-datacenter does not lead to this policy being used (contrary to the documentation which states that "By default, this property is not set resulting in Datastax's standard round robin policy being used"). Instead when I don't set it, DcAwareRoundRobin policy is used, but the local-datacenter is inferred to be the AZ of the first node of contact points list
 - Writing custom ConfigSessionProvider seems to fix the aforementioned issue (i.e. RoundRobin policy is used), but simply overriding the clusterBuild method by calling super.clusterBuild() and setting the load balancing policy seems to lead to all other config values (set in the application.conf) being lost.

Is there a proper way of setting the load balancing policy?

```
public class RoundRobinLoadBalancingConfigSessionProvider extends ConfigSessionProvider {
    public RoundRobinLoadBalancingConfigSessionProvider(ActorSystem system, Config config) {
        super(system, config);
    }

    @Override
    public Future<Cluster.Builder> clusterBuilder(String clusterId, ExecutionContext ec) {
        Future<Cluster.Builder> originalClusterBuilderFuture = super.clusterBuilder(clusterId, ec);
        return originalClusterBuilderFuture.map(originalClusterBuilder -> originalClusterBuilder.withLoadBalancingPolicy(new RoundRobinPolicy()), ec);
    }
}
```

```
cassandra-journal {
    session-provider= "com....RoundRobinLoadBalancingConfigSessionProvider
    read-consistency = "TWO"
    write-consistency = "TWO"
}
```

```
    cassandra-snapshot-store {
    session-provider= "com....RoundRobinLoadBalancingConfigSessionProvider
    read-consistency = "TWO"
    write-consistency = "TWO"
}
```
The aforementioned code leads to read/write consistency levels being disregarded. However, they are working fine when not setting the `session-provider` value
I'm using version 0.51

**Comment by chbatey** [comment]
This wasn't the intended extension point but it should work fine.

I'm surprised that leads to the consistency levels being ignored as they are set directly on the prepared statements: 

https://github.com/akka/akka-persistence-cassandra/blob/v0.51/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L94

How are you validating the consistency is ignored?
