### ISSUE TITLE
eventsByTag fails after upgrading from version 0.54 to 0.85 

### ISSUE THREAD

**Issue by hervandevliert** [akka/akka-persistence-cassandra#356]
After upgrading from version 0.54 to 0.85 the _eventsByTag_ source gives message "_Missing event for new persistence id: ???. Expected sequence nr: 1, actual: ???._"

## Scenario:
1. One or more event are persisted
2. eventsByTag is started with an offset (offset after persisting Event 1).
3. New Event is persisted

**Expected**
eventsByTag provides Event that is persisted in step 3

**Actual**
eventsByTag provides NO Event and shows following INFO message:
"Missing event for new persistence id: ???. Expected sequence nr: 1, actual: ???." 

## Reproduction steps
To reproduce this issue I added a modified version of _EventsByTagRestartSpec_ that includes a new test that should run fine but fails.

[EventsByTagRestartSpec.scala.txt](https://github.com/akka/akka-persistence-cassandra/files/2084274/EventsByTagRestartSpec.scala.txt)

**Comment by chbatey** [comment]
Hi @hervandevliert are you still seeing issues in the latest version (0.103). There are been a lot of improvements to events by tag since 0.85
