### ISSUE TITLE
Cross build for Scala 2.13.0 milestones

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-persistence-cassandra#364]
It would be nice to have 2.13.0-M3 cross-built releases of Akka Persistence Cassandra so downstream dependents (such as Lagom) can test with the 2.13 milestones.

(Also 2.13.0-M4, pending https://github.com/akka/akka/issues/25105)

**Comment by ktoso** [comment]
Yes good point

**Comment by chbatey** [comment]
@TimMoore let me know if this is blocking you and we can bump it up

**Comment by TimMoore** [comment]
Not blocking. Scala 2.13 support is a low priority for us, but I've been trying to at least chase down dependencies so that we don't have to discover them all after 2.13 GA. Feel free to hold off until you're ready.

Thanks for asking!

**Comment by SethTisue** [comment]
is it time to revive this?

**Comment by patriknw** [comment]
yes, we should

**Comment by SethTisue** [comment]
so the cross-build is added, would it be helpful to the Play/Lagom team to have an actual artifact published for M5?
