### ISSUE TITLE
can not persist in future for ..yield block

### ISSUE THREAD

**Issue by wanghuatao** [akka/akka-persistence-cassandra#375]
this is my code:
for(info <- future) yield{
  persist(someEvent){evt => 
    dosomething.// sometimes can not work
 }
}

when I call persist(someEvent){evt => dosomething} in future block,sometimes it can not work.

**Comment by chbatey** [comment]
Please ask questions on https://discuss.lightbend.com/c/akka

`persist` should only be called from the Actor thread. Not a Future callback.
