### ISSUE TITLE
Received Done when in idle state

### ISSUE THREAD

**Issue by struijenID** [akka/akka-persistence-cassandra#382]
We are currently using Akka Persistence Cassandra 0.87 (akka 2.5.13) in our application. While testing, the following logline pops up quite often:

```
2018-08-16 09:37:08,169 ERROR - akka.persistence.cassandra.journal.TagWriter                     - Received Done when in idle state. This is a bug. Please report with DEBUG logs: TagWriteDone(Map(PersistenceId-AkkaBroadcasterUtil-AkkaBroadcasterActor-12 -> PidProgress(208649,208649,1,e4d9a120-9fcd-11e8-a373-8b46395557f3)),None)
```

What are the implications of this bug?

We enabled DEBUG logging on Akka and Akka Persistence Cassandra. You can find the logs here: 
- Node 1 (this is the one that logged the line above): https://www.dropbox.com/s/aoa2uesvoy09xoe/akka-1.log.gz?dl=0
- Node 2 (forms a cluster with node 1): https://www.dropbox.com/s/vbmoqy4gqoyacrd/akka-2.log.gz?dl=0

**Comment by struijenID** [comment]
I can also confirm this is still an issue in 0.88.

**Comment by chbatey** [comment]
Looking at the logs it looks like two actors with the persistenceId `PersistenceId-AkkaBroadcasterUtil-AkkaBroadcasterActor-12` ran at the same time. Is that a sharded actor? How do you pick its persistenceId?

**Comment by struijenID** [comment]
We have not seen this logline pop up the past few months.

A week or so after I created this issue, we did find and fix a bug that was causing presistence IDs to be calculated incorrectly. As a result persistence IDs were being reused when they should not have been.

Thank you for taking the time to review this issue. I am closing it :)

**Comment by chbatey** [comment]
Thanks for confirming @struijenID
