### ISSUE TITLE
Cassandra compatibility

### ISSUE THREAD

**Issue by pjan** [akka/akka-persistence-cassandra#39]
Hi,

we had an issue today with the 0.8 release in conjunction with cassandra 2.1.7 as well as 2.1.9. The following error was reported:

```
java.lang.IllegalStateException: Unset value at index 5.
If you want this value to be null, please set it to null explicitly.
```

Bumping cassandra to 2.2.4 resolved it for us. Just so you know/are aware of this

**Comment by patriknw** [comment]
This is a duplicate of https://github.com/akka/akka-persistence-cassandra/issues/35
I have just released 0.9 which should fix this. Will be available at maven central shortly
