### ISSUE TITLE
Invalid query when removing the messages in ScyllaDB

### ISSUE THREAD

**Issue by btomala** [akka/akka-persistence-cassandra#395]
I'm playing around with ScyllaDB and the `akka-persistence-cassandra`. I discovered a bug (from the Scylla perspective only) in a query responsible for deleting messages.

This query cause the problem:
```cql
> delete from messages where persistence_id = 'user-529' and partition_nr = 0 and sequence_nr <= 9;
InvalidRequest: Error from server: code=2200 [Invalid query] message="A range deletion operation needs to specify both bounds"
```

This query works well:
```cql
> delete from messages where persistence_id = 'user-529' and partition_nr = 0 and sequence_nr >= 0 and sequence_nr <= 9;
```

Here is a problematic query https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/CassandraStatements.scala#L231

It is a quick fix, and it should work for both DBs. Is it ok for you to fix it? I can rise a PR with it.

**Comment by chbatey** [comment]
I don't see a problem with that
