### ISSUE TITLE
test on JDK 9+?

### ISSUE THREAD

**Issue by SethTisue** [akka/akka-persistence-cassandra#398]
at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/352/consoleFull I'm seeing

```
[akka-persistence-cassandra] Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 23
[akka-persistence-cassandra] 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116) ~[na:na]
[akka-persistence-cassandra] 	at java.base/java.lang.String.substring(String.java:1885) ~[na:na]
[akka-persistence-cassandra] 	at org.github.jamm.MemoryLayoutSpecification.getEffectiveMemoryLayoutSpecification(MemoryLayoutSpecification.java:190) ~[cassandra-bundle.jar:0.86-dbuildx06d340fb6398c1dd05bb4c5e1f8faf50363b5bcc]
[akka-persistence-cassandra] 	at org.github.jamm.MemoryLayoutSpecification.<clinit>(MemoryLayoutSpecification.java:31) ~[cassandra-bundle.jar:0.86-dbuildx06d340fb6398c1dd05bb4c5e1f8faf50363b5bcc]
[akka-persistence-cassandra] 	... 16 common frames omitted
```

that's on JDK 9. I don't currently know whether 10 and 11 are also affected. (after Java 11 final is out, I'll start using it instead)

**Comment by TimMoore** [comment]
The challenge is that Cassandra itself doesn't support running on Java >8 until Cassandra 4.0 (which is not yet released). This project would need to gain the ability to launch Cassandra using a different `JAVA_HOME` than the one running the build & tests.

**Comment by SethTisue** [comment]
ahhh, okay. well, good to know.

**Comment by ennru** [comment]
The tests run on AdoptOpenJDK 8 and 11 nowadays.
