### ISSUE TITLE
Consider removing timebucket from messages table

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#399]
Or perhaps just the primary key. It was added for the materialized view eventsByTag impl which we've now removed.

**Comment by patriknw** [comment]
Does this mean that we would remove it from default table definition, but still look for the column in and adjust statements to if if the column is defined or not?

I'm not sure it's worth it?

**Comment by patriknw** [comment]
This might help for working around the CosmosDB delete problem https://github.com/akka/akka-persistence-cassandra/issues/764

It should be possible to only have the timebucket in the tag view, created by the tag writer from the timeUuid.
