### ISSUE TITLE
EventsByTag: Memory consumption keeps increasing when using unbounded number of persistence ids

### ISSUE THREAD

**Issue by ksmolder** [akka/akka-persistence-cassandra#410]
In our application we are currently tagging events written by actors which have a limited lifetime but are unbounded in number (for example: an HTTP call results in the creation of a new instance of this persistent actor and the events persisted by these actors are tagged).

According to our investigation, Memory consumption keeps increasing in this scenario. When analyzing, we saw that the TagWriter contains a Map (sequenceNrs) holding ScalaTuples. One field of these tuples seems to be the persistent id, the other a number which seems to us to be the sequence number (we're no Scala guru's). It also looks like there are only entries added to this map and not removed.

So is it correct that event tagging should only be activated for a limited number of persistence ids, or is the use case of an unbounded set of persistence ids supported. In case unbounded should work, is there any advice on how the memory size of the (sequenceNrs) map can be estimated and kept under control?

**Comment by chbatey** [comment]
Thanks for the detailed report @ksmolder 

You're right we keep around a small object per persistenceId in the TagWriter keeping track of the expected sequenceNr.

I think your use case is valid so we could garbage collect these, perhaps we can watch the persistent actors as the datastrucutre is re-populated when an actor recovers.
