### ISSUE TITLE
EventsByTag gap-timeout and eventual-consistency-delay

### ISSUE THREAD

**Issue by struijenID** [akka/akka-persistence-cassandra#424]
In v0.91 the cassandra-query-journal.events-by-tag.eventual-consistency-delay config option was added. I am confused about what its significance is in relation to cassandra-query-journal.events-by-tag.gap-timeout and  potentially not processing delayed events.

Until recently, my assumption was that gap-timeout is an interval of time during which events that are received out of order from Cassandra, can be reordered before they are returned to the EventsByTag query. For instance, if the Cassandra cluster returns events with sequence number [1,2,4, 5] then akka persistence cassandra will wait a maximum of _gap-timeout_ amount of time before assuming the event with sequence number 3 got lost/never happened. If the event with sequence number 3 does turn up before this time, the EventsByTag query will return [1,2,3,4,5]. If not, [1,2,4,5].

It was also my understanding that eventual-consistency-delay was a sort of implicit sleep before the results are returned to EventsByTag queries. In other words, once the query is running, each event is delayed _eventual-consistency-delay_ amount of time before it is returned to EventsByTag query.

Tests have shown that this is not entirely the case. Setting the eventual-consistency-delay to 100ms, and the gap-timeout to 10s meant that EventsByTag queries would not return all events often times, much like described in https://github.com/akka/akka-persistence-cassandra/issues/383

Furthermore the reference.conf of akka persistence cassandra states the following about eventual-consistency-delay: "[...] if this offset is saved for restarting the query the delayed events will never be processed." I interpreted that delayed events can only be skipped if the application or EventsByTag query is stopped, which does not happen in my test scenarios.

Initially, I was relucatant to increase the eventual-consistency-delay timeout because I inferred that it would slow down my application. Nonetheless, I ran a test with the eventual-consistency-delay configured to 5s and gap-timeout set to 10s. All events were successfully reported and my application did not slow down in a measurable way.

To me it is clear that I am not interpreting the configuration options correctly. What is the correct interpretation of the both the gap-timeout and eventual-consistency-delay properties?

Thanks!

PS: my test setup consists of 3 akka cluster nodes that are backed by a cassandra cluster with 5 nodes and a replication factor of 3.

**Comment by patriknw** [comment]
Sorry for delay in responding here. Have you also seen the description in https://github.com/akka/akka-persistence-cassandra/blob/master/EventsByTag.md#consistency

In summary. `eventual-consistency-delay` means that it will not read the very latest tail of events but lag behind to be able to collect delayed events before sorting and delivering them. This gives a better global ordering of the events.

`gap-timeout` is used when it has detected a hole in the sequence numbers, e.g. [1, 2, 4]. It will never deliver 4 without 3. It will look for 3 during the `gap-timeout` and then fail the stream if not found.

Do you have anything to add @chbatey ?

**Comment by chbatey** [comment]
Two scenarios we need a `eventual-consistency-delay` rather than just relying on the `gap-timeout` is:
* for persistenceIds that we haven't seen yet in the events by tag stream that aren't starting from sequenceNr1
* for when we miss a delayed event for a known sequence nr but then there isn't another one for some time so we don't know there is a gap

**Comment by chbatey** [comment]
Let's leave this open and make sure this is covered in the docs

**Comment by chbatey** [comment]
Both scenarios have improved with the back-tracking PR and we've improved the docs to describe how these settings work
