### ISSUE TITLE
EventsByTag query: duplicate sequence number warnings after a Split Brain

### ISSUE THREAD

**Issue by franbh** [akka/akka-persistence-cassandra#430]
The eventsByTag query seems to be stuck after a Split Brain has occurred, logging the same warning over and over again every 3 seconds:
`Duplicate sequence number. Persistence id: XXX. Tag: YYY. Expected sequence nr: 418. Actual 1. This will be dropped.`

How can this be fixed?

**Comment by chbatey** [comment]
That log doesn't fail the stream it just highlights that you have duplicate sequence nrs. 

What behaviour do you want for a fix? Something like the replay filter for a persistent actor for the read side? https://doc.akka.io/docs/akka/2.5/persistence.html#replay-filter 
Or do you want an automated tool to clean up a log? If so you'd need to be in control of which events are deleted / kept.

Having multiple actors run with the same persistenceId usually means you'll have broken the invariant of your actor as most logic inside an actor is based on the current state which will be incorrect if multiple are running at the same time.

**Comment by chbatey** [comment]
Closing in favour of https://github.com/akka/akka-persistence-cassandra/issues/578
