### ISSUE TITLE
Migration tool cannot handle custom config namespaces

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-cassandra#432]
The `EventsByTagMigration` utility uses the default config namespace (`cassandra-journal`) and does currently not support specifying a custom namespace for the config to use making it impossible to migrate such a database.

**Comment by milanvdm** [comment]
@johanandren Thanks for picking this up.
If you need any assistance testing your solution, let me know.

**Comment by johanandren** [comment]
@milanvdm there's now a 0.93-snapshot that you can try out, something like this with sbt:

```
resolvers +=
  "Akka Snapshots" at "https://repo.akka.io/snapshots"

libraryDependencies := Seq(
  "com.typesafe.akka" %% "akka-persistence-cassandra" % "0.93-SNAPSHOT"
)
```
