### ISSUE TITLE
Consistency level "ONE" by default in cassandra-snapshot-store can be too weak.

### ISSUE THREAD

**Issue by thomschke** [akka/akka-persistence-cassandra#438]
The read/write consistency level by default in cassandra-snapshot-store is "ONE". 

https://github.com/akka/akka-persistence-cassandra/blob/8090f4db3d60e614ad9bce4d1ae38b2f07e0e34c/core/src/main/resources/reference.conf#L532-L536

Depending on the current event rate and snapshot interval this default value can be too weak and should be changed to "QUORUM".

**Comment by patriknw** [comment]
I think it would only be a problem if you are deleting events too eagerly, otherwise it shouldn't matter if it doesn't see the latest snapshot since it will just start from an older snapshot and replay events from there. Do I miss something?

**Comment by thomschke** [comment]
Hi @patriknw, I agree with your comment: `read-consistency = "ONE" ` is enough, because the common case for akka-persistence is "append-only events". And if snapshot data can be lost then `write-consistency = "ONE"` is enough too. Sorry for my ill-considered question.

**Comment by patriknw** [comment]
no problem, thanks for asking

**Comment by patriknw** [comment]
I'll add the rationale to the comment in reference.conf
