### ISSUE TITLE
batch covering many partitions for tag_scanning

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#442]
```
WARN  10:08:45 Unlogged batch covering 72 partitions detected against table [keyspace1.tag_scanning]. You should use a logged batch for atomicity, or asynchronous writes for performance.
```

Reported by @franbh, thanks

**Comment by franbh** [comment]
A bit more context on this issue:
- akka-persistence-cassandra 0.91 or 0.93 depending on the microservice
- akka 2.5.18
- lagom 1.4.7: we are using sharded tags for `ReadSideProcessors` (currently 20 shards), and usually multiple `PersistentEntities` per microservice.
- C* 3.0.16

**Comment by thomschke** [comment]
Same issue:

- akka-persistence-cassandra 0.94
- akka 2.5.22
- lagom 1.5.0 (shared tags with 9 shards)
- cassandra 3.11.4

**Comment by manuelbernhardt** [comment]
Same issue:

- akka 2.5.22
- cassandra driver 4.0.0
- akka-persistence-cassandra 0.96
- cassandra 3.9

Coming up during load testing:

```WARN  [Native-Transport-Requests-2] 2019-05-24 10:33:33,475 NoSpamLogger.java:94 - Unlogged batch covering 500 partitions detected against table [akka.tag_scanning]. You should use a logged batch for atomicity, or asynchronous writes for performance.```

**Comment by thomschke** [comment]
cassandra property `unlogged_batch_across_partitions_warn_threshold` (Default 10)

**Comment by patriknw** [comment]
Reopened to port to release-0.x branch
