### ISSUE TITLE
Does Cassandra Journal write-retries work as intended in case of NoHostAvailable exception?

### ISSUE THREAD

**Issue by darshak28** [akka/akka-persistence-cassandra#443]
@pwilby, @chbatey ,@patriknw : I have one question regarding Journal writes. We are testing behaviour of write-retries and read-retries of Cassandra-journal and the question is whether it works as intended in-case of NoHostavailable exceptions? We are following below test steps and we are seeing journal writes fails. [since Persistent Actor dies]

**Scenario:**
1)Start the application (this will cause the keyspaces to be created)
2)Send event [ which started Persistent actor]
3)Event processed and seeing data in persistence table
4)Kill cassandra
5)Send event
6) Wait for a minute and start cassandra - [write failed no data in Persistence table for new event] [seeing NoHosatAvailable exception]

**Note :There is only one Caasnadra node.**

What my understading is regarding write-retries is : It will try to attempt write operation in Casandra DB no.of times whatever value we set of write-retries [i.e. write-reties = 12345].
Please correct me if my understanding is wrong and provide your thoughts on this.

[ Consider me as new bie in this area :) ]

**Comment by chbatey** [comment]
Sorry that we didn't respond here.

No i don't think that retries happen when there is a NoHostAvailable. The retry policy in the driver only acts on Read/Write timeout which means it has to have communicated with a coordinator node or an unavailable exception.
