### ISSUE TITLE
Optimization to avoid HighestDeletedSequenceNumber query from metadata table

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#449]
If an application is not using deletes it is unnecessary to query the metadata table for highest deleted sequence number. We can have a config option to opt out from deletes and then skip that query on recovery.

**Comment by jrudolph** [comment]
Is that table updated only for deletes done using the persistence API? In that case, we should then prevent the delete API from being used if that config option is set, right?

**Comment by patriknw** [comment]
Exactly, if this flag is set then we would reject any delete attempts. It can't protect against deletes made in the past before setting the flag ("you have to know what you are doing").

**Comment by jrudolph** [comment]
> It can't protect against deletes made in the past before setting the flag

Could we add a single check on startup of the entity to prevent that situation?

**Comment by jrudolph** [comment]
> > It can't protect against deletes made in the past before setting the flag
> 
> Could we add a single check on startup of the entity to prevent that situation?

I guess not because that would do the same amount of work than we are trying to avoid.

**Comment by patriknw** [comment]
exactly, and I don't think we can do a single query to check if the table is empty, because of the partitioning by persistenceId primaryKey
