### ISSUE TITLE
Snapshot deletion does not work when an actor has more than 65535 snapshots.

### ISSUE THREAD

**Issue by thehutgroup-adamryan** [akka/akka-persistence-cassandra#450]
### Versions used 
akka-persistence-cassandra: 0.25
akka: 2.4.16

### Expected Behavior
When calling the deleteSnapshots method in an Akka Actor with a criteria containing a minimum and maximum snapshot sequence number these should be deleted in the database in an efficient manner.

### Actual Behavior
If the difference between the minimum and maximum snapshot sequence numbers is greater than 65535 then an exception is raised in com.datastax.driver.core.BatchStatement#add of "Batch statement cannot contain more than " + 0xFFFF + " statements.".
This occurs because the snapshot deletions are a batch of single deletions for each snapshot sequence number. This is a very inefficient query and would be much quicker by constructing a single query with a (less-than greater-than) where clause.
There is a work around to the above in the application by calling the deleteSnapshots method  with blocks of sequence numbers below the above limit. This however is still not ideal as if the snapshot number is sufficiently large it raises another issue where the sheer number of batched deletions causes increased garbage collection Cassandra to the point where it starts dropping read requests. On my local machine this was in the region of 2.5m snapshots.

###
I would like to understand if this is being done for a particular reason or if it is simply a case of no one encountering it thus far. If this is the case I can see a work around to the issue and would be happy to raise a PR.

**Comment by chbatey** [comment]
Hi @thehutgroup-adamryan this looks to be for historical reasons when Cassandra did not support range deletions. It was changed for message deletions to support both: https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/CassandraStatements.scala#L235

But has never been done for snapshots. Would you like to raise a PR?

**Comment by thehutgroup-adamryan** [comment]
I've put up an initial commit to look over.

**Comment by chbatey** [comment]
Leaving this open until we've ported it to master
