### ISSUE TITLE
events not stored in tag_views, tag_write_progress and tag_scanning

### ISSUE THREAD

**Issue by umbreak** [akka/akka-persistence-cassandra#457]
### Versions used 

0.92, 0.93, 0.94 and 0.95 (latest)

### Expected Behavior

When an event gets stored in the **messages** table, it should get stored in the tables **tag_views**, **tag_write_progress** and **tag_scanning** (as long as the event has a tag associated to it).

### Actual Behavior

When creating events in a burst fashion ( 15 events/second or more) sometimes the events do not get stored in any of the tables: tag_views, tag_write_progress or tag_scanning.

```
select COUNT(*) from messages where persistence_id='id1' ALLOW FILTERING;
 count
-------
     1

select COUNT(*) from tag_scanning where persistence_id='id1' ALLOW FILTERING;
 count
-------
     0

select COUNT(*) from tag_views where persistence_id='id1' ALLOW FILTERING;
 count
-------
     0

select COUNT(*) from tag_write_progress where persistence_id='id1' ALLOW FILTERING;
 count
-------
     0
```

It doesn't matter how long we wait, the missing events won't go to those tables. They only appear in them whenever we explicitly visit them (if from cassandra we fetch the specific id).

We have tried lowering those configuration values:

```
cassandra-journal {
  events-by-tag {
    max-message-batch-size = 150
    flush-interval = 250ms
    scanning-flush-interval = 30s
  }
}
```

with little success (it seems to help in some scenarios, but when injesting more events/s it continues to drop some events).

**Comment by milanvdm** [comment]
We have the exact same issue. We opened a commercial support ticket for this.

**Comment by johanandren** [comment]
Hi @umbreak, it would be great if you could provide some more details: do you see any warnings or errors in the logs, is there any other configuration you have changed from the defaults?

**Comment by umbreak** [comment]
I've re-run some tests and it does not show any error/warning log, even though after pushing 3000 events, there is one missing. Some other times it shows some error logs like

```
2019-04-24 06:54:03 WARN  a.p.cassandra.journal.TagWriters - Unknown persistent actor terminated. Please raise an issue with debug logs. Pid: [resources-my-persistence-id-1]. Ref: [Actor[akka://kg-1-0-2/system/sharding/resources/1/my-persistence-id-1#1569994481]]
2019-04-24 06:54:04 INFO  c.e.b.n.s.i.stream.StreamCoordinator - Received initial start value of type 'Offset', with value 'TimeBasedUUID(42208820-3061-11e9-ac6d-15a1ea4b923e)' running the indexing function across the element stream
2019-04-24 06:54:08 ERROR akka.actor.OneForOneStrategy - Watch(Actor[akka://kg-1-0-2/system/cassandra-journal/tagWrites#-803075704], Actor[akka://kg-1-0-2/system/sharding/resources/1/my-persistence-id-2#-1706959827]) termination message was not overwritten from [Some(PersistentActorTerminated(resources-d5abbf1d-e28d-42c2-8c72-18cff997291c-https%3A%2F%2Fbluebrain.github.io%2Fnexus%2Fvocabulary%2FdefaultSparqlIndex,Actor[akka://kg-1-0-2/system/sharding/resources/1/my-persistence-id-2#-1706959827]))] to [Some(PersistentActorTerminated(resources-my-persistence-id-2,Actor[akka://kg-1-0-2/system/sharding/resources/1/my-persistence-id-2#-1706959827]))]. If this was intended, unwatch first before using `watch` / `watchWith` with another message.
java.lang.IllegalStateException: Watch(Actor[akka://kg-1-0-2/system/cassandra-journal/tagWrites#-803075704], Actor[akka://kg-1-0-2/system/sharding/resources/1/my-persistence-id-2#-1706959827]) termination message was not overwritten from [Some(PersistentActorTerminated(resources-d5abbf1d-e28d-42c2-8c72-18cff997291c-https%3A%2F%2Fbluebrain.github.io%2Fnexus%2Fvocabulary%2FdefaultSparqlIndex,Actor[akka://kg-1-0-2/system/sharding/resources/1/my-persistence-id-2#-1706959827]))] to [Some(PersistentActorTerminated(resources-my-persistence-id-2,Actor[akka://kg-1-0-2/system/sharding/resources/1/my-persistence-id-2#-1706959827]))]. If this was intended, unwatch first before using `watch` / `watchWith` with another message.
    at akka.actor.dungeon.DeathWatch.checkWatchingSame(DeathWatch.scala:130)
    at akka.actor.dungeon.DeathWatch.watchWith(DeathWatch.scala:48)
    at akka.actor.dungeon.DeathWatch.watchWith$(DeathWatch.scala:39)
    at akka.actor.ActorCell.watchWith(ActorCell.scala:429)
    at akka.persistence.cassandra.journal.TagWriters$$anonfun$receive$1.applyOrElse(TagWriters.scala:164)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at akka.persistence.cassandra.journal.TagWriters.akka$actor$Timers$$super$aroundReceive(TagWriters.scala:116)
```

However, the resources shown on the error are not related to the events which do not appear on the tag_* tables. So I guess that's something different.

You can obtain our cassandra configuration [here](https://github.com/BlueBrain/nexus-kg/blob/master/src/main/resources/cassandra.conf).

**Comment by johanandren** [comment]
Which version was that error with, looks like it may be an actual clue (line doesn't match up with 0.96 which is what the repo says)?

The tag writer is shared for the journal, so error for unrelated events could potentially still be trouble.

**Comment by umbreak** [comment]
That error I picked up from our production environment, which is 0.92

**Comment by johanandren** [comment]
Ok, the interesting part would be to see errors from 0.95 and later since there was fixes around htis, I think that particular error was fixed by #447

**Comment by chbatey** [comment]
Hi @umbreak what do you mean by `if from cassandra we fetch the specific id`? Do you mean doing a cassandra query makes them show up? Could you send an example query? 

Or do you mean restarting a persistent actor for that id makes them show up?

If it is the former then that is very strange behaviour from Cassandra. If it is the latter it sounds like for some reason the events aren't getting flushed due to either the ActorSystem or PersistentActor shutting down or https://github.com/akka/akka-persistence-cassandra/pull/447 and are then being fixed on startup of that persistent actor the next time.

Could you share a bit more about the test you are running e.g. when you ingest, are then shutting down the persistent actor or actor system afterwards?

**Comment by umbreak** [comment]
What I mean by `if from cassandra we fetch the specific id` is:
```scala
PersistenceQuery(as).readJournalFor[CurrentEventsByPersistenceIdQuery](config.readJournalPluginId)
      .currentEventsByPersistenceId("my-persistence-id", 0L, Long.MaxValue).(...)
```

I'm trying to reproduce once more the error, but right now I can't make it happen. I'll continue testing

**Comment by chbatey** [comment]
I wouldn't expect running a `currentEventsByPersistenceId to fix the tag_* tables. Only recovering a persistent actor runs the reconciliation process

**Comment by milanvdm** [comment]
We had the same behavior though. When we ran a `by-id` query on akka-persistence, the event with that persistence_id appeared in the tag_view afterwards.

**Comment by chbatey** [comment]
@umbreak can you let us know if you see this in the latest version? We believe this to be fixed but let us know if you see issues

**Comment by umbreak** [comment]
Is it fixed for @milanvdm ? We are still trying to reproduce the issue and so far we haven't been able to do it anymore.

**Comment by milanvdm** [comment]
@umbreak For us, the latest version fixed the issue.

**Comment by umbreak** [comment]
So I guess this can be closed
