### ISSUE TITLE
How long the eventual-consistency-delay should be set for eventsByTag query

### ISSUE THREAD

**Issue by thirdteeth** [akka/akka-persistence-cassandra#459]
Hi team,
we have an application with multiple node akka cluster use akka persistent as write side and use eventsByTag query to get events form cassandra journal, processed and stored in elastic search as read side.

we set the cassandra-journal.pubsub-notification=on and eventual-consistency-delay=0 to reduce the delay of events go to read side, but there are events lost in the query, 

I found a ticket https://github.com/akka/akka-persistence-cassandra/issues/383 that said eventual-consistency-delay should be >0, but how long it should be to at least does not lost events and also make the events go to read side as fast at it can.

Thanks

**Comment by patriknw** [comment]
Related to https://github.com/akka/akka-persistence-cassandra/issues/460

**Comment by chbatey** [comment]
Hi @thirdteeth I've added some extra comments in #470, mainly to the reference.conf regarding why eventual consistency is so important and included a recommendation of at least 2s
