### ISSUE TITLE
Possibility to use Cassandra Cluster Metrics

### ISSUE THREAD

**Issue by SamanSattari** [akka/akka-persistence-cassandra#46]
Feature request:
After connecting to Cassandra,  session has a registry of metrics. These metrics give insight into Cassandra cluster performance. It would be nice to have the option to retrieve these metrics from session in order to push to a Graphite Server.

**Comment by patriknw** [comment]
What would the API look like? You want it to be accessible from your Akka application/PersistentActor?

**Comment by SamanSattari** [comment]
If metric registry could be retrieved, then the client application can decide in what medium they use the metrics (graphite, log, etc.). 
So I was thinking in CassndraJournal and CassandraSnapshotStore can be implement by: 
```
private object CassandraJournal {
  private case object Init
  case object GetMetricRegistry
}
```
Or something similar.
and in CassandraReadJournal there can be an additional method that retrieves registry.

**Comment by patriknw** [comment]
ok, that would be an Akka extension then. Makes sense.

**Comment by SamanSattari** [comment]
Is it OK if I work on it?

**Comment by patriknw** [comment]
Absolutely, contributions are welcome.

**Comment by merlijn** [comment]
@SamanSattari 

Are you actively working on this? If not, I (or rather, we) can pick this up. We really require this feature for our application and could get time to make a PR.

**Comment by SamanSattari** [comment]
@merlijn Hi I am almost done with it. I will make the pull request today or tomorrow.

**Comment by merlijn** [comment]
@SamanSattari Great, thanks for the quick response!
