### ISSUE TITLE
too large batches

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#48]
Due to the removal of the `max-message-batch-size` in https://github.com/akka/akka/issues/19694 we can easily hit the max batch size limit (batch_size_fail_threshold_in_kb).

`CassandraJournalPerfSpec` blows up with `max-message-batch-size = 500`.

**Comment by magro** [comment]
@patriknw FYI: C* currently mistakenly applies the batch_size_fail_threshold_in_kb to single partition batches as well, this will be changed/fixed with https://issues.apache.org/jira/browse/CASSANDRA-10876.

**Comment by patriknw** [comment]
Thanks, that is good to know.
