### ISSUE TITLE
Travis job gets duplicated

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-persistence-cassandra#485]
there’s something off on the `.travis.yml` (https://github.com/akka/akka-persistence-cassandra/blob/master/.travis.yml) and one job gets duplicate. See https://travis-ci.org/akka/akka-persistence-cassandra/builds/538596061?utm_source=github_status&utm_medium=notification or the modified version without scala 2.11 https://travis-ci.org/akka/akka-persistence-cassandra/builds/539242335?utm_source=github_status&utm_medium=notification.

**Comment by dwijnand** [comment]
It's also running whitesource while using Scala 2.11.

**Comment by ennru** [comment]
Fixed with #496
