### ISSUE TITLE
Remove `DateTieredCompactionStrategy`

### ISSUE THREAD

**Issue by ennru** [akka/akka-persistence-cassandra#502]
### Short description

`DateTieredCompactionStrategy` has been deprecated since version 0.56 and should be removed prior to 1.0.

**Comment by jewertow** [comment]
It was resolved in #588. Issue should be closed.

**Comment by patriknw** [comment]
Thanks, let's add a note to the migration guide and then this ticket can be closed.

**Comment by jewertow** [comment]
I see that the information already exists in migration guide (https://github.com/akka/akka-persistence-cassandra/blob/master/docs/src/main/paradox/migrations.md#removals).

**Comment by patriknw** [comment]
excellent
