### ISSUE TITLE
Document testing. Launcher vs test containers vs external C*

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#536]
Perhaps we should just recommend https://www.testcontainers.org/modules/databases/cassandra/ rather than maintaining our launcher? Either way document usage.

**Comment by ennru** [comment]
Our experience with Testcontainers in Alpakka is very positive.

**Comment by ihostage** [comment]
Hi, folks! 👋 
Do you plan to migrate to Testcontainers on `1.0`?

**Comment by chbatey** [comment]
I think we should document how to do testing with test containers for 1.0. Any advantages to noving our tests? I wouldn't want to start one c* per test, that was too slow in the past.
