### ISSUE TITLE
Resolve Cassandra's host and port dynamically

### ISSUE THREAD

**Issue by huntc** [akka/akka-persistence-cassandra#54]
[Akka Persistence Cassandra](https://github.com/akka/akka-persistence-cassandra) presently assumes that a Cassandra cluster is accessible at a fixed set of IP addresses. While this may be the case for large Cassandra clusters, it is likely so for smaller Cassandra clusters that are associated with microservices.

This problem can be resolved by handling a `Future[Option[(InetAddress, Int)]]` each time a connection is required. We had to solve a similar issue with our internal contrail library. contrail now looks for an actor responsible for service location via actor selection if config declares that this is what we must do. Otherwise we declare a successful future that returns the static host and port of config.

**Comment by magro** [comment]
Just a thought: wouldn't it be more generic to allow to inject a Session? Then this SessionProvider can do what it wants. The default one would just build upon the existing configuration.

**Comment by patriknw** [comment]
@magro that is an interesting thought, I'll take a look at that when completing this

**Comment by masterzen** [comment]
+1 for injecting the Session, that would allow a node to share a Session for some other code not using Akka Persistence.
