### ISSUE TITLE
The configured EventAdapters are not used by the CassandraReadJournal queries

### ISSUE THREAD

**Issue by filosganga** [akka/akka-persistence-cassandra#55]
Given a configuration:

```
cassandra-journal {
  event-adapters {
    protobuf = "com.mypackage.ProtoEventAdapter"
  }

  event-adapter-bindings {
    “com.mypackage.PersistedEvent" = protobuf
    "com.google.protobuf.MessageLite" = protobuf
  }
}
```

The configured event adapters are used only to write to the journal and when a event is replayed in a PersistentActor. They are not used by the CassandraReadJournal queries.

The LevelDbReadJournal call the configured event-adapters also for queries instead.

**Comment by patriknw** [comment]
That is a good observation, thanks.

**Comment by filosganga** [comment]
I have digged a little into LevelDb implementation:
LevelDb implement the ReadJournal on top of the LeveldbJournal, so it will use the existing private `adaptFromJournal` method from the base Journal class. The Cassandra plugin instead do the reverse and implement the CassandraJournal on top of the query system, that seems a reasonable approach to me.

Is it not possible to apply EventAdapter after you got the EventEnvelope as you have lost the manifest information, so it should be done before.

**Comment by patriknw** [comment]
@filosganga  I agree, would you like to contribute with a pull request?

**Comment by filosganga** [comment]
I would love to. I have already started looking into that.

**Comment by patriknw** [comment]
thanks

**Comment by andrea-zoleo** [comment]
Hi,

I have the same (I think) problem using eventsByTag call.

To use it, I need a TaggingEventAdapter registered on events-adapter to wrap events Tagged(...) envelope, but the  TaggingEventAdapter is not used.

There is an alternative approach in order to have eventsByTag working for CassandraReadJournal ?

**Comment by patriknw** [comment]
It's the same with all queries.

`akka.persistence.journal.Tagged` is special though, it's unwrapped on the write side, before storing

**Comment by andrea-zoleo** [comment]
I don't know if i have understood @patriknw answer, 
but as workaround, I persist directly a Tagged(myEvent,..) instead of myEvent, 
skipping the need of custom TaggingEventAdapter.

**Comment by patriknw** [comment]
That was not my intention. You can still use an event adapter on the write side that wraps the events in `akka.persistence.journal.Tagged` and since that is not stored like that the lack of event adapter on the query side does not matter for `Tagged`.

**Comment by andrea-zoleo** [comment]
I'm unable to configure my EventAdapter for cassandra.
In my application.conf I have put:
akka {
  persistence {
    journal {
      plugin = "cassandra-journal"
      cassandra-journal {
        event-adapters {
          tagging        = "mypkg.TaggingEventAdapter"
        }
        event-adapter-bindings {
          "services.account.AccountsActor.EmailConfirmed" = tagging
        }
      }
    }
  }
}

but it is not used during store of services.account.AccountsActor.EmailConfirmed event.
Have I done some mistake?

**Comment by patriknw** [comment]
is `AccountsActor.EmailConfirmed` scala? if it's in the companion object the class name is `services.account.AccountsActor$EmailConfirmed`

**Comment by andrea-zoleo** [comment]
Ok, I have fixed the event name in config, but it still doesn't work.
There is somewhere a cassandra / EventAdapter code example with config file that I can explore?

**Comment by patriknw** [comment]
https://github.com/filosganga/akka-persistence-cassandra/blob/wip-%2355-query-event-adapters/src/test/scala/akka/persistence/cassandra/query/EventsByTagSpec.scala#L51

Your config is in wrong section, it should be:
```
akka {
  persistence {
    journal {
      plugin = "cassandra-journal"
    }
  }
}

     cassandra-journal {
        event-adapters {
          tagging        = "mypkg.TaggingEventAdapter"
        }
        event-adapter-bindings {
          "services.account.AccountsActor$EmailConfirmed" = tagging
        }
      }
 ```

**Comment by andrea-zoleo** [comment]
That fixes it! 
Thanks a lot, you are a Hero!
My wrong assumption about config came from akka docs:
```
akka.persistence.journal {
  inmem {
    event-adapters {
      tagging        = "docs.persistence.MyTaggingEventAdapter"
      user-upcasting = "docs.persistence.UserUpcastingEventAdapter"
      item-upcasting = "docs.persistence.ItemUpcastingEventAdapter"
    }
 
    event-adapter-bindings {
      "docs.persistence.Item"        = tagging
      "docs.persistence.TaggedEvent" = tagging
      "docs.persistence.v1.Event"    = [user-upcasting, item-upcasting]
    }
  }
}
```
in [Akka docs](http://doc.akka.io/docs/akka/2.4.1/scala/persistence.html#Event_Adapters).

**Comment by filosganga** [comment]
Because the `akka.persistence.journal.inmem` is the `journalPluginId`

**Comment by acmoune** [comment]
@filosganga @patriknw , Sorry to comeback to it, I don't know if the initial issue was fixed. Still not able to read previously persisted protobuf messages. I am using `akka 2.5.19` and `akka-persistence-cassandra 0.98`.

This is my Protobuf adapter code:

```scala
class AccountProtobufAdapter extends EventAdapter {
  override def manifest(event: Any): String = event.getClass.getName
  def eventType(event: Any): String = ???
  def entityType = ???

  override def toJournal(event: Any): Any = event match {
    case e: EntityEvent =>
      println(s"Writing to journal: $e") // THIS MESSAGE IS DISPLAYED
      
      val message = e match {
        case AccountCreated(account) =>
          AccountDataModel.AccountCreated.newBuilder.setAccount(...).build
        ...
      }
      
      Tagged(message, Set(entityType, eventType(e)))

    case _ => throw new RuntimeException(s"Protobuf adapter can not write type: $event")
  }

  override def fromJournal(event: Any, manifest: String): EventSeq = {
    println(s"Reading from journal, Event: $event, manifest: $manifest") // THIS MESSAGE IS NEVER DISPLAYED

    event match {
      case message: Message =>
        message match {
          case m: AccountDataModel.AccountCreated =>
            EventSeq.single(AccountCreated(fromAccountDM(m.getAccount)))
          ...
        }

      case _ => throw new RuntimeException(s"Protobuf adapter can not read type: $event")
    }
  }
}
```
And this is my config:

```
cassandra-journal {
  contact-points = [${cassandra.host}]
  port = ${cassandra.port}
  tags = {
    account = 1
    accountcreated = 2
    ...
  }

  event-adapters{
    proto = "AccountProtobufAdapter"
  }

  event-adapter-bindings{
    "EntityEvent" = proto
    "com.google.protobuf.Message" = proto
  }
}

cassandra-snapshot-store {
  contact-points = [${cassandra.host}]
  port = ${cassandra.port}
}

akka {
  actor {
    serializers {
      proto = "akka.remote.serialization.ProtobufSerializer"
      json = "net.africaunity.commons.persistence.JsonSerializer"
    }

    serialization-bindings {
      "com.google.protobuf.Message" = proto                 # for events
      "EntityState" = json                                  # for snapshots
    }
  }

  persistence {
    journal.plugin = "cassandra-journal"
    snapshot-store.plugin = "cassandra-snapshot-store"
  }
}
```

It looks like the adapter is not consulted when reading. According to @patriknw it should not be a problem, but how do we get the extracted event then ?
