### ISSUE TITLE
Configuration not shown in the docs

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-persistence-cassandra#553]
It seems https://github.com/akka/akka-persistence-cassandra/blob/v0.99/docs/src/main/paradox/journal.md intends to show the `reference.conf` but it doesn't:

![image](https://user-images.githubusercontent.com/9868/66032630-02bcc180-e506-11e9-91d4-dfd712dcf4c3.png)

**Comment by jrudolph** [comment]
Also for the snapshots page.

Shouldn't there also be more documentation about things you might want to configure?

**Comment by ennru** [comment]
The colon indicates this intention, but it reference conf was never shown there (see [0.98](https://doc.akka.io/docs/akka-persistence-cassandra/0.98/journal.html)).
The docs were just migrated from the readme we had earlier, which couldn't do includes.

**Comment by jewertow** [comment]
It should be closed.

**Comment by patriknw** [comment]
Thanks
