### ISSUE TITLE
Reset of tagseqnr before sendMissingTagWrite

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#572]
In https://github.com/akka/akka-persistence-cassandra/issues/562 we handled the BulkTagWrite. Could there be a similar problem for the TagWrite messages that are sent from a few places? If the actor is terminated before the sendMissingTagWrite?

**Comment by chbatey** [comment]
Agreed, let's share the same logic for forwarding a tag write whether it be a single one or part of a bulk tag write
