### ISSUE TITLE
Enable test for Akka Typed again, and add eventsByTag testing for Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#573]
might deserve a separate test module with 2.6 dependency?

**Comment by patriknw** [comment]
for example to cover the sender issue fixed in https://github.com/akka/akka/pull/28060

**Comment by ennru** [comment]
We can set up a scheduled build with Akka 2.6 as we do in Alpakka projects.

**Comment by patriknw** [comment]
the complexity is that it must be a separate module with different 2.6 dependencies

**Comment by chbatey** [comment]
And we don't currently compile against 2.6 as we have deprecations

**Comment by chbatey** [comment]
Was done in the driver PR
