### ISSUE TITLE
Automated release / publish from travis

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#575]
This was started when we were working on 1.0 of this plugin. The publish was not working so I've removed it in https://github.com/akka/akka-persistence-cassandra/pull/574

Re-introduce when we work on 1.0

**Comment by ihostage** [comment]
Hi, @chbatey! 👋 
Some time ago we work on the like task for [Play SOAP](https://github.com/playframework/play-soap). 
Until it's not merged, but it's tested and worked. 
Part 1 - https://github.com/playframework/play-soap/pull/87
Part 2 - https://github.com/playframework/play-soap/pull/89
Maybe this example can help to save time to resolve the issue. 😉

**Comment by chbatey** [comment]
Closed by https://github.com/akka/akka-persistence-cassandra/pull/650
