### ISSUE TITLE
Events by tag reconciliation tool

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#578]
If the user has a split brain and continues to write on both sides due to an improper downing provider. Or there is a bug in the plugin that results in tag pid sequence numbers are corrupted then the tag_views table needs rebuilt.

An initial version could drop / re-create the table. More complicated versions could fix/reconcile the table.

At the very least for 1.0 we should support stopping the app, dropping the re-creating the table as that is what we had for materialized views.

**Comment by patriknw** [comment]
Initial version merged, so closing this. Might be additional follow up improvements.
