### ISSUE TITLE
Read journal client metrics category doesn't match config path in multi-plugin

### ISSUE THREAD

**Issue by migesok** [akka/akka-persistence-cassandra#579]
### Versions used 

Akka Persistence Cassandra version: 0.62, master 

### Expected Behavior

When several read journal plugin instances configured Cassandra client metrics for each of them should get metrics categories matching their respective plugin instances config paths.

### Actual Behavior

Current implementation generates metrics categories for read journal like this:
```
s"${CassandraReadJournal.Identifier}$categoryUid"
```
Where `categoryUid` is an atomic counter, thus it makes metrics paths depend on runtime initialization order of plugin instances. 
It makes the metrics for read journal useless in multi--plugin scenario as you never know which metrics are for which plugin instance. Also it doesn't match the behaviour for write and snapshot store plugins which just use config path to distinguish between different metrics instances.

### Solution

I checked the code and it appears that there was a related ticket created for Akka: akka/akka#19822
It was fixed even before Akka 2.5 but for some reason subsequent changes haven't been made in Akka Persistence Cassandra.
I will shortly contribute PR's with fixes for `master`. I also can contribute an PR for `release-0.50`, as my currently used version is an internal fork of 0.62.

**Comment by migesok** [comment]
Created PR's for `master` and `release-0.50`: #580, #581

**Comment by chbatey** [comment]
Thanks @migesok I'll take a look at the PRs now
