### ISSUE TITLE
The allPersistenceIds() query returns all the configured tags as well.

### ISSUE THREAD

**Issue by filosganga** [akka/akka-persistence-cassandra#58]
The queries `allPersistenceIds()` and `currentPersistenceIds()` return also the configured tags.

**Comment by patriknw** [comment]
@filosganga I can't reproduce this and I see nothing in the code that indicates that it would include tags in `allPersistenceIds()`.

I tried to add the following in the `EventsByTagSpec` and it does not fail:
```scala
      val src = queries.currentPersistenceIds()
      src.runWith(TestSink.probe[Any])
        .request(10)
        .expectNextUnordered("a", "b", "persistenceInit")
        .expectComplete()
```

**Comment by filosganga** [comment]
Hi Patrik,
I will try to reproduce it today. If it doesn't happen anymore we can close
this issue

**Comment by patriknw** [comment]
@filosganga please reopen if this is still a problem
