### ISSUE TITLE
Clarify schema setup in documentation

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-persistence-cassandra#582]
The schema is printed in the documentation or you can set `tables-autocreate` but overall, ops-related topics are not really discussed in the documentation.

There should be section that details how the usual installation and maintenance (migration) operations should take place and also what kind of compatibility guarantees the plugin gives in general (e.g. no migrations necessary for major/minor versions).

Also the schema printed in the documentation should be exactly the same as the one in the code and not a copy.

**Comment by patriknw** [comment]
Also describe that for production keyspace and tables should be created manually with a script before starting the application. Cassandra doesn't like when those are created at the same time from several nodes, which can happen if running an Akka Cluster.
