### ISSUE TITLE
Document setting target partition sizes

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#603]
We group events into c* partitions if a persistence id has more than `target-partition-size` the events are partitioned across c* partitions.

The default value for this is 50000, good c* practice is to keep partitions under 100mb, perhaps 400mb for 3.11 onwards. See https://thelastpickle.com/blog/2019/01/11/wide-partitions-cassandra-3-11.html

That leaves 200 bytes per events, is that realistic? Should we make it 10000 to make it less likely users will hit wide partitions. C* will warn when they grow too a few hundred megs.

**Comment by chbatey** [comment]
Existing uses would need to override the default to the old value as it can't be changed

**Comment by patriknw** [comment]
Sounds good to have a better default, but changing it is scary. Can we detect misconfiguration? I think we had some storage of the configured size in the meta-data table but removed that?

**Comment by chbatey** [comment]
Perhaps we should just document that for new projects try a smaller one. Users will already be changing their config for the upgrade

**Comment by patriknw** [comment]
Not sure what our conclusion is here. Worth documenting if we don't dare to change the default.

**Comment by chbatey** [comment]
Agreed let's not risk changing the default but add a doc to say for new apps consider a different value
