### ISSUE TITLE
Support Connect Cassandra from different network 

### ISSUE THREAD

**Issue by thirdteeth** [akka/akka-persistence-cassandra#604]
### Short description

Support Connect Cassandra from a different network

### Details

As Cassandra Cluster Builder has a method withAddressTranslator to translate actual Cassandra node addresses to the addresses the driver should use if the Cassandra nodes are behind a router and are not accessed directly, it would be better we can provide a default AddressTranslator that load the mapping from the configuration file and set it to Cassandra Cluster builder during initial Cluster

**Comment by patriknw** [comment]
I think this is possible by implementing a custom CassandraSessionProvider, and it hasn't came up often enough to include in default implementation.

In 1.0 we have updated the datastax-java-driver and maybe it already supports this via configuration.
