### ISSUE TITLE
Cleanup unused tagPidSequenceNr in EventsByTagStage

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#605]
Can become a problem to keep all persistenceIds in memory if many short lived persistenceId. Should be possible to cleanup old unused ids there.

**Comment by chbatey** [comment]
Once it is dropped we won't know if it is a first time persistence id or has been dropped so it'll trigger a search for missing events. 

In the use case of a short lived persistence id this will never happen.

For a usecase that involves infrequent events for persistenceIds, at worse, this could happen for every event.

We could use something like a bloom filter to keep track of dropped persistenceIds? Perhaps the time to drop persistneceIds for being configurable would be enough to prevent the search happening often for most use cases?

**Comment by chbatey** [comment]
Also I think the timeout has to be bigger than the bucket size * 2. Otherwise the missing search will go back and find previous events and re-deliver them
