### ISSUE TITLE
Last events may not be delivered by eventsByTag

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#606]
When eventsByTag is progressing the offset because events originating from one node are visible but events from another node are delayed, the delayed events may not be delivered. Note that it can be the tag writing that is delayed, not necessarily on the Cassandra server side.

They will be found by a later gap detection, but if there are no more events for that persistenceId (for a long time) they will not be found.

The risk for this happening increases when the eventual-consistency-delay is decreased.

I think we need some additional scanning for older events to find these.

Slightly related https://github.com/akka/akka-persistence-cassandra/issues/402

**Comment by francescaLonedo** [comment]
We are experiencing this issue in production environment. Is there any workaround we can apply until it gets fixed?

**Comment by rogueai** [comment]
I think I'm hitting the same issue, events from an `eventsByTag` query stop being processed

**Comment by chbatey** [comment]
@francescaLonedo to not set the eventual consistency delay too low, what do you have it to?

**Comment by chbatey** [comment]
@rogueai this won't stop all events being processed. Only new ones for persistenceIds that had delayed events greater than the eventual consistency delay.

**Comment by chbatey** [comment]
Closed by https://github.com/akka/akka-persistence-cassandra/pull/634 and will be in the next 0.x release and 1.0
