### ISSUE TITLE
EventsByTagStage stop pulling periodically after searching for missing events. 

### ISSUE THREAD

**Issue by liao0007** [akka/akka-persistence-cassandra#609]
### Versions used 

Akka version: 2.6.1
akka-persistence-cassandra tag:v0.101

### Expected Behavior

EventsByTagStage periodically pulls from journal store with refreshInterval defined.

```
// akka.persistence.cassandra.query.EventsByTagStage:272
refreshInterval match {
  case Some(interval) =>
    val initial =
      if (interval >= 2.seconds)
        (interval / 2) + ThreadLocalRandom.current().nextLong(interval.toMillis / 2).millis
      else interval
    schedulePeriodicallyWithInitialDelay(QueryPoll, initial, interval)
    log.debug("[{}] Scheduling query poll at: {} ms", stageUuid, interval.toMillis)
  case None =>
    log.debug("[{}] CurrentQuery: No query polling", stageUuid)
}
```

### Actual Behavior

With some cases when 'scheduleOnce' is called, for example, when looking for missing events: 

```
// akka.persistence.cassandra.query.EventsByTagStage:605
 // the new persistence-id scan time is typically much smaller than the refresh interval
 // so do not wait for the next refresh to look again
 if (timeLeft < settings.refreshInterval) {
   scheduleOnce(QueryPoll, timeLeft)
 } else if (!isLiveQuery()) {
   // a current query doesn't have a poll schedule one
   scheduleOnce(QueryPoll, settings.refreshInterval)
 }
```

The periodical timer by timerKey 'QueryPoll' which was originally scheduled in the preStart part

```
// akka.persistence.cassandra.query.EventsByTagStage:278
schedulePeriodicallyWithInitialDelay(QueryPoll, initial, interval)
```

is canceled and replaced by this one shot timer.

Hence after one final execution "continue()", EventsByTagStage will no longer to pulling events from journal store any more.

**Comment by chbatey** [comment]
Thanks for reporting. The simplest thing would be to use a different key for the one off polls. Would you be up for raising a PR?

**Comment by liao0007** [comment]
Hi chbatey, thanks for the fast reply.

If it is identified as a bug, I would think It as a very serious problem, as it will cause the readside never gets updated, also any subscription to the event stream will never get updated events.

I am wondering why nobody raise any issue regarding this yet?

##


> The simplest thing would be to use a different key for the one off polls

I don't think it would be that easy to just use a different timer key for the one off polls. Because EventsByTagStage maintains a mutable internal state: 

```
//akka.persistence.cassandra.query. EventsByTagStage:188
var stageState: StageState = _
```

During polling, this state is mutatted accordingly. Multiple scheduled tasks running at the same time will eventually cause race condition for this internal state.

I suggest to fix it by continue using the same "QueryPoll" timer key, but reschedule it right after those one off polls finishes?

**Comment by chbatey** [comment]
Hi @liao0007 

Only one timer will be executed at a time as it is using the built in timer support rather than scheduling a task and the stage can be in any state when a poll comes in so it is fine if a one off poll has started a query and then the periodic poll is executed.

> I am wondering why nobody raise any issue regarding this yet?

The one off poll was added quite recently and it is only triggered in certain scenarios so not everyone will hit this

**Comment by chbatey** [comment]
Something like https://github.com/akka/akka-persistence-cassandra/pull/611 should fix it

**Comment by liao0007** [comment]
Hi @chbatey 

Thanks for info and the code, that exactly solved the problem!

**Comment by chbatey** [comment]
Let's keep this open to get it merged into master

**Comment by chbatey** [comment]
https://github.com/akka/akka-persistence-cassandra/pull/627
