### ISSUE TITLE
default first-time-bucket too far back

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#619]
Could we have a default value that means that it's calculated from current date, for example 2 weeks back?

The default of 20151120 will result in a lot of queries when starting up first time.

**Comment by chbatey** [comment]
The risk is that over time an application stops working, I don't think we can assume that users always do a NoOffset query and then move to an offset after

**Comment by patriknw** [comment]
Closing, since it's simple enough for user to define an offset based on time. See https://github.com/akka/akka-samples/pull/188
