### ISSUE TITLE
Not adjacent sequence number in EventsByTagPublisher

### ISSUE THREAD

**Issue by andrea-zoleo** [akka/akka-persistence-cassandra#66]
Hi,
using CassandraReadJournal, eventsByTag stream correctly push the tagged event to the stream consumer when in an actor I write a first tagged event in the Journal via persist call, 
but when I write a second tagged event, the stream push nothing and after 30 seconds the system logs:
[error] ...-a.p.c.q.EventsByTagPublisher: query chunk aborted for tag [...], timBucket [20160222],  expected sequence number [14] for [...], but got [15].

**Comment by patriknw** [comment]
You don't tag all events? Probably you persisted 13 and 15 with the tag, but 14 was not tagged. That is indeed an oversight by me.

**Comment by andrea-zoleo** [comment]
You are right. I don't tag all events, but the only ones for those I want the views to be updated.
Is it mandatory to tag all events?

**Comment by patriknw** [comment]
this is a bug, I'll fix it tomorrow
