### ISSUE TITLE
Repo not searchable

### ISSUE THREAD

**Issue by matlockx** [akka/akka-persistence-cassandra#67]
Unfortunately this repo is a fork which means that it is not searchable by default until it gets more stars than the parent fork (afaik). 
Maybe the parent fork can be deleted (but I do not know whether it solves the problem) or this repo can be deleted and re-created without the fork link?

**Comment by patriknw** [comment]
what do you mean by searchable? what search is that?

**Comment by matlockx** [comment]
Use the github search on the gihtub.com page for this repo. Search for something that should be there, e.g. timebucket and you do not find a thing although there are a lot of code lines containing the word timebucket

**Comment by jypma** [comment]
Just ran into this as well. I tend to use Github search quite a bit for a "quick search" for keyword, class etc. in source code, for repos that I don't have readily cloned.

@krasserm Do you know of a creative way to enable the `akka/akka-persistence-cassandra` repo to be searchable?

**Comment by TimMoore** [comment]
This is resolved now.
