### ISSUE TITLE
Drop support for Cassandra 2.x in 1.0

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#670]
We have some workarounds to support both and this would simplify the internals a bit.

**Comment by patriknw** [comment]
@chbatey do you think this is ok, or too aggressive?

**Comment by chbatey** [comment]
It's still a supported Cassandra version, both 2.1 and 2.2: http://cassandra.apache.org/download/. 

Our compat mode for deletes I think may be for 2.0? Let's check and drop 2.0? It doesn't cost us much if the driver supports all the versions

**Comment by patriknw** [comment]
I agree, closing for now.
