### ISSUE TITLE
Also test with Cassandra 2.2.x

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#691]
Since we say that we still support that.

**Comment by patriknw** [comment]
Tried locally with 2.2.15. Some test failures:

* akka.persistence.cassandra.EventsByTagRestartSpec
* akka.persistence.cassandra.EventsByTagCrashSpec
* akka.persistence.cassandra.compaction.CassandraCompactionStrategySpec
* akka.persistence.cassandra.EventsByTagMigrationSpec
* akka.persistence.cassandra.EventsByTagMigrationProvidePersistenceIds

```
[info] CassandraSessionSpec:
[info] session
[info] - must create indexes *** FAILED *** (162 milliseconds)
[info]   The future returned an exception of type: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException, with message: Keyspace system_schema does not exist. (CassandraSessionSpec.scala:73)

CassandraJournalPerfSpec
Batch of prepared statements for [cassandrajournalperfspec.messages] is of size 36136, exceeding specified threshold of 5120 by 31016.

EventsByTagStressSpec
Batch of prepared statements for [eventsbytagstressspec.tag_views] is of size 9075, exceeding specified threshold of 5120 by 3955.
```

**Comment by chbatey** [comment]
Let's do this in a cron job as not to add so much time to the PR validation. We're unlikely to break things regularly

**Comment by chbatey** [comment]
One oddity is that materialized views were only added in 3.0 so old versions of the plugin required cassandra 3 and now newer versions can work with 2.2 again
