### ISSUE TITLE
0.11 Failing to connect to cassandra db

### ISSUE THREAD

**Issue by yoseldvp** [akka/akka-persistence-cassandra#70]
I've been using the 0.7 version of the plugin so far without much problems. Since we are writting a new application, we decided to go with the newer version, but now the plugin is unable to connect to our dev cassandra database.

The message i get is:

`Failed to connect to Cassandra and initialize. It will be retried on demand. Caused by: All host(s) tried for query failed (tried: /172.30.255.78:9042 (com.datastax.driver.core.exceptions.TransportException: [/172.30.255.78] Error writing))`

This error is not consistent though, i would get this the 90% of the times i run the code. Just FWIW the 0.7 version of the plugin works fine.

**Comment by patriknw** [comment]
@yoseldvp thanks for reporting, but I have no clue what can be causing this. We have not seen any such problems. What version of Cassandra server are you using?

**Comment by yoseldvp** [comment]
I was using cassandra 3.0.2.

**Comment by patriknw** [comment]
Ok, good. How can we reproduce it?

**Comment by patriknw** [comment]
@yoseldvp any news here?

**Comment by yoseldvp** [comment]
Sorry for the delayed answer. The connection to cassandra is working pretty good now, seems like it was some discovery issues due to the infrasctructure the app was running on. 

Thanks

**Comment by patriknw** [comment]
Thanks for the update, then I'll close this.
0.12 is released now, by the way.
