### ISSUE TITLE
Document how to delete events from tag table

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#716]
When deleting all events for a persistenceId the corresponding events in tag view table are not deleted. That is good, and documented.

We should complement that documentation with how to delete from tag view table. Maybe the reconciler tool can be used? TTL can be another approach if the tag table is only for transient storage to update a different read model or publish to another system.

**Comment by chbatey** [comment]
I think we now do offer deletion so we can close this
