### ISSUE TITLE
deadlock in cassandra-snapshot-store plugin

### ISSUE THREAD

**Issue by minisaw** [akka/akka-persistence-cassandra#72]
i have 10 persistent actors, and a cassandra-snapshot-store enabled.

upon system startup, akka persistence issues a LoadSnapshot message to the snapshot store for each of my actors (10 messages total).

they all try acquiring a cassandra connection at CassandraSnapshotStore:55:
55: private[this] lazy val cassandraSession: CassandraSession

by default, the journal's "default-dispatcher" has parallelism-max = 8

in my case this means that 7 threads park on the lazy val's initialization monitor, and the remaining one tries to do the initialization, but alas! it needs to wait for a Future to complete at ConfigSessionProvider:85:

84:  def clusterBuilder(clusterId: String)(implicit ec: ExecutionContext): Future[Cluster.Builder] = {
85:    lookupContactPoints(clusterId).map { cp =>

the problem is that the map function does not get executed because there are no threads remaining in the default dispatcher's thread pool (it seems to be configured to be executed by the same default dispatcher).

naturally, in case i raise the parallelism-max to above 10, everything starts working fine, like so:

cassandra-snapshot-store {
...
  default-dispatcher {
...
    fork-join-executor {
...
      parallelism-max = 16

**Comment by minisaw** [comment]
there is also this message observed in logs that might be pertinent to the issue:

ERROR [...-cassandra-snapshot-store.default-dispatcher-12][i.n.util.ResourceLeakDetector][] - LEAK: You are creating too many HashedWheelTimer instances.  HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.

**Comment by patriknw** [comment]
Thanks for reporting. The blocking initialization is indeed a problem and it will be solved by issue https://github.com/akka/akka-persistence-cassandra/issues/6
It's my top priority issue for this project.

**Comment by kpbochenek** [comment]
I started to use snapshots and deadlocking on start sounds very bad.

CassandraSnapshotStore is an actor and on PreStart we can see:
 `self ! CassandraSnapshotStore.Init`

And receive is simply synchronous initialization of session:
`case CassandraSnapshotStore.Init => try { cassandraSession }`

but there is also a part of receive:
`case LoadSnapshot(persistenceId, criteria, toSequenceNr) ⇒ ...`
which under the hood executes:
`for { mds <- Future(metadata(persistenceId, criteria).take(3).toVector) ... `
and getting metadata calls `session` but it is done asynchronously.

So when SnapshotStore receives more `LoadSnapshot` than it is threads in a pool and also before `CassandraSnapshotStore.Init` is received then it can deadlock, right?

Is it possible to assure `CassandraSnapshotStore.Init` will be a first message processed by actor?
Or maybe it would be okay to start with 'uninitialized' state and handle only "Init" message and then 
"become" to normal Receive method?
Is it possible to get rid of `CassandraSnapshotStore.Init` message and enforce eager initialization i.e. on `RecoveryCompleted`? 
Or a third idea, in receive where LoadSnaphost message is handled we should first check if "sessionUsed" is true, and if not just initialize session (before going asynchronous). 
This will obviously block, but we already block on `CassandraSnapshotStore.Init` message.

Not sure what is a state of issue #6 but if it is not going to be very soon would it be possible to add one of mentioned workarounds for now?

**Comment by patriknw** [comment]
I agree that we must fix this. I will make sure that it fits in next sprint, starting on monday.

**Comment by patriknw** [comment]
Pull request: https://github.com/akka/akka-persistence-cassandra/pull/74
