### ISSUE TITLE
404 for source links in 0.x (wrong `-doc-source-url`?)

### ISSUE THREAD

**Issue by adriaanm** [akka/akka-persistence-cassandra#729]
Looks like there is an issue with source links in https://doc.akka.io/api/akka-persistence-cassandra/0.103/akka/persistence/cassandra/ -- clicking on `package.scala` I get a 404: `https://github.com/akka/akka-persistence-cassandra-1.x/tree/v0.103/core/src/main/scala/akka/persistence/cassandra/package.scala#L1`.

Note the `-1.x` in the URL -- I guess it's from https://github.com/akka/akka-persistence-cassandra/blob/v0.103/project/Common.scala#L64. This was fixed for 1.0.0-M0 by https://github.com/akka/akka-persistence-cassandra/pull/496/files#diff-c275e43e5d4ef31cb36384dbbf818da8R64

**Comment by ennru** [comment]
#804 fixes this in the release-0.x branch and I re-published the 0.103 documentation with those fixes applied.

**Comment by ennru** [comment]
Fixed with #804
