### ISSUE TITLE
EventsByPersistenceIdStage:420 (v0.62): NullPointerException when deserializing event

### ISSUE THREAD

**Issue by arbitrary-dev** [akka/akka-persistence-cassandra#734]
We use v0.62 and sometimes experience NPE's during C* unavailability (timeouts/latencies):

```
ERROR a.a.RepointableActorRef Error in stage [akka.persistence.cassandra.query.EventsByPersistenceIdStage@bfa6fe4]: null
java.lang.NullPointerException: null
	at akka.persistence.cassandra.journal.CassandraJournal$EventDeserializer.deserializeEvent(CassandraJournal.scala:529)
	at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.extractEvent(EventsByPersistenceIdStage.scala:420)
	at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.tryPushOne(EventsByPersistenceIdStage.scala:361)
	at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.onPull(EventsByPersistenceIdStage.scala:312)
	at akka.stream.impl.fusing.GraphInterpreter.processPull
```

- [CassandraJournal$EventDeserializer.deserializeEvent(CassandraJournal.scala:529](https://github.com/akka/akka-persistence-cassandra/blob/v0.62/core/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L529)
- [EventsByPersistenceIdStage$$anon$1.extractEvent(EventsByPersistenceIdStage.scala:420](https://github.com/akka/akka-persistence-cassandra/blob/v0.62/core/src/main/scala/akka/persistence/cassandra/query/EventsByPersistenceIdStage.scala#L420)

C* journal contains these records, and `event` field is defined for them.

Can you suggest where/what could be the problem?

**Comment by patriknw** [comment]
Historically it was stored in the "message" columns as serialized `PersistentRepr, but then we changed to the "event" column as serialized event payload. From the stack trace it looks like the "event" column is null, and the "message" column is also null. I don't know how that can happen. 

Can you inspect the `messages` table with `cqlsh` to see what is stored there for the failing persistenceId?

Does it always happen for a specific persistenceId or is that random?

**Comment by arbitrary-dev** [comment]
>Can you inspect the messages table with cqlsh to see what is stored there for the failing persistenceId?
We inspected the `messages` data, and `event` column for the failing persistenceId is present and not null.

>Does it always happen for a specific persistenceId or is that random?
Randomly happens during C* unavailability (latencies/timouts)

**Comment by patriknw** [comment]
That is strange, maybe fixed by a later version of the driver. I would anyway recommend that you update to 0.104. 1.0.0 will also be released soon. Migration guide https://doc.akka.io/docs/akka-persistence-cassandra/snapshot/migrations.html
