### ISSUE TITLE
compilation error with latest Akka

### ISSUE THREAD

**Issue by SethTisue** [akka/akka-persistence-cassandra#772]
context: https://github.com/scala/community-build/pull/1128

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1360/artifact/logs/akka-persistence-cassandra-build.log

```
[akka-persistence-cassandra] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.16/project-builds/akka-persistence-cassandra-f350d141194911d9dd0328166cb4f9285cd7c21e/core/src/test/scala/akka/persistence/cassandra/journal/CassandraJournalSpec.scala:71:33: wrong number of arguments for pattern akka.persistence.JournalProtocol.WriteMessagesFailed(cause: Throwable, writeCount: Int)
[akka-persistence-cassandra] [error]         case WriteMessagesFailed(cause) => cause
[akka-persistence-cassandra] [error]                                 ^
[akka-persistence-cassandra] [error] one error found
[akka-persistence-cassandra] [error] (core / Test / compileIncremental) Compilation failed
```

looks like it started with akka/akka@96639c537ee74f12f9fd31a85a8bf256f27a51cd

it would be nice to get this straightened out at some point so I can keep tracking newer Akka in the community build, but there's no particular rush

**Comment by chbatey** [comment]
This should have been caught in the cron builds that test against the latest Akka. I'll take a look. Thanks for reporting

**Comment by chbatey** [comment]
@SethTisue 

This is fixed in master but the community build runs against the release-0x branch by the looks of it.
This made sense as that was our main development branch but master is about to become that with the release of 1.0.

Shall we change the community build to run against master?

**Comment by SethTisue** [comment]
I _was_ on master, I froze at v0.100 because of this problem, but perhaps the fix hadn't been made at that time.

let's try moving to newer SHAs at https://github.com/scala/community-build/pull/1130

closing, since in this repo, the problem is fixed
