### ISSUE TITLE
akka.persistence.typed.internal.JournalFailureException: Exception during recovery. Last known sequence number [0]. PersistenceId [abc], due to: null

### ISSUE THREAD

**Issue by CedrusZhao** [akka/akka-persistence-cassandra#787]
### Versions used 

Akka version: 2.6.5
akka-persistence-typed：2.6.5

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

### Relevant logs

[https://discuss.lightbend.com/t/exception-during-recovery-last-known-sequence-number-0-persistenceid-abc-due-to-null/6638](url)

**Comment by patriknw** [comment]
Looks like it was solved, based on the comment at discuss.
