### ISSUE TITLE
EventsByTagMigration batching of flushes

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-persistence-cassandra#795]
It seems the `periodicFlush` would specify a batch size with which to flush. To do this is uses a `buffer` element:

https://github.com/akka/akka-persistence-cassandra/blob/08c122fef95dda745faae7f1d3e98cf4f36eea57/core/src/main/scala/akka/persistence/cassandra/EventsByTagMigration.scala#L213-L214

However, that won't create batches but still just runs one flush per element, it basically only has an impact on the backpressure but not on the rate of flushes. Is that intended or should a `grouped` operator be used instead?

**Comment by chbatey** [comment]
Yes this should use grouped 👍
