### ISSUE TITLE
reverse sort in selectHighestSequenceNr 

### ISSUE THREAD

**Issue by nathanleyton** [akka/akka-persistence-cassandra#801]
I see that in selectHighestSequenceNr there is DESC order on sequence_nr which will pull all the records to memory and reverse sort them from the clustering column order. This is a little bit of an anti pattern as I understand (correct me if I am wrong). The effect of this is that in Scylla it will hit a configured limit for this as they protect the system with a maximum . See:-

https://docs.scylladb.com/troubleshooting/reverse-queries/ 

In cassandra we don't see such a hard configured limit, however I have read that they also handle this in memory and that it is also discouraged due to performance and eventual OOM issues. I do wonder if I am missing something as this would surely have come up in the past. 

Does anyone know if I am missing something here and if not perhaps there is a better way? 

Thanks

**Comment by patriknw** [comment]
Thanks for reporting. We should look into this.

Maybe related article: https://thelastpickle.com/blog/2017/03/07/The-limit-clause-in-cassandra-might-not-work-as-you-think.html

**Comment by nathanleyton** [comment]
I guess changing this code would fix the issue:-

`def selectHighestSequenceNr =
    s"""
     SELECT max(sequence_nr) FROM $tableName WHERE
       persistence_id = ? AND
       partition_nr = ?
   """`

**Comment by nathanleyton** [comment]
I would like to point the test cases to my local Scylla to see how it does and maybe fix up any other issues. Could you give me a pointer of how to tell the tests to use my local instance and not create an inplace Cassandra? 

Thanks

**Comment by chbatey** [comment]
Won't max still bring everything into memory on the coordinator? Also bumps our min C* version

**Comment by nathanleyton** [comment]
As far as I can tell it doesn't , not in Scylla at least. I also witnessed a performance improvement in your unit tests that use including with Cassandra. Give it a try.

**Comment by nathanleyton** [comment]
I just did some much deeper testing and tracing on both Cassandra and Scylla. Scylla simply cannot function with the large reverse sort as everything goes to memory and they have hard limits, however it seems to be able to do the max without dumping everything in to memory but it does scan the table. Cassandra behaves differently, it listens to the limit first and takes the bottom of the list and seems very efficient at it. the execution time was very similar until I added 500K messages then the traces were showing more rational results. I think the truth is that Scylla is handling reverse sort with limit badly and both handle max the same. Sorry for the inaccuracy in my previous message, I hadn't properly tested on Cassandra until this morning. I think I will need to make the call to use Cassandra rather than Scylla on our system until Scylla can fix reverse sort with limit. I will report to them also. Thanks for your time.

**Comment by patriknw** [comment]
Thanks for deeper look. We could optionally define a different query for Scylla. We already have a compat setting for Cosmos I think.

Keeping everything in memory indeed seems suboptimal for sorting with limit. Keeping the ”best” rows should be enough.

**Comment by nathanleyton** [comment]
Its a temporary fix at best, max can get a little poor in terms of performance with larger partitions. There is an open issue: https://github.com/scylladb/scylla/issues/6307  I made a comment, Scylla team may fix this one it seems.
