### ISSUE TITLE
Cassandra 2.2 doesn't work for cleanup tool

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#830]
The cleanup tool uses a query that is only supported in C* 3.0+

We have a nightly cron that catches this as it runs with 2.2.

I think we should just say the tool only works on C* 3+ rather than put effort into a C* version that is very old and about to drop off support when 4.0 is released.

If we do this we need to tag the test and not have it run in the 2.2 build.

**Comment by chbatey** [comment]
FYI it is the range delete for snapshots

**Comment by patriknw** [comment]
> I think we should just say the tool only works on C* 3+

I agree
