### ISSUE TITLE
Snapshots @ Sonatype (Travis?)

### ISSUE THREAD

**Issue by briantopping** [akka/akka-persistence-cassandra#85]
Looks like the build is configured to push to Sonatype, but there are no snapshots there. Does this project need to be added to Travis?

**Comment by patriknw** [comment]
Do we need snapshots? I'd rather publish real releases often. Sorry for the delay of 0.12. We were investgating some serious bugs, that most likely were due to old Cassandra version. I'll publish 0.12 on Monday, or earlier.

**Comment by briantopping** [comment]
Thanks Patrik, no need to apologize, I was just needing to eliminate a dependency on `com.typesafe.akka:akka-cluster-tools_2.11:2.4.2`. 

This is a dependency that changes a lot in my project, so I thought it would be good to have access to snapshots. We'll live either way :)

**Comment by patriknw** [comment]
Closing this for now. We might start with snapshots after 1.0, but now we can easily cut new 0.x releases when needed. 0.12 has been released now.
