### ISSUE TITLE
slow eventsByTag when many new persistence ids

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#851]
Reported by @mckeeh3 when using the Where on Earth app.

When restarting the app (e.g. new deployment) and then create/delete devices in an area on the map that had previously been used the projection is very slow.

The reason is that the persistenceIds exists since before and therefore the new events seqNr doesn't start at 1. Then the eventsByTag query is looking for missing event during the `new-persistence-id-scan-timeout` (default 100ms).

Attached is log from a very clear example where I have set the new-persistence-id-scan-timeout=1s and creating 16 devices.

[log39-79ad2edd-2960-47cd-b66e-051ec8983ce0.txt.gz](https://github.com/akka/akka-persistence-cassandra/files/5688656/log39-79ad2edd-2960-47cd-b66e-051ec8983ce0.txt.gz)

I'm not sure we can improve this, but maybe it would be possible to keep track of that a "look for missing" had just been done and then it wouldn't have to scan for the entire new-persistence-id-scan-timeout for subsequent pids.

**Comment by patriknw** [comment]
Workaround is to reduce or disable (0s) new-persistence-id-scan-timeout

```
akka.persistence.cassandra.events-by-tag {
  new-persistence-id-scan-timeout = 0s
  cleanup-old-persistence-ids = 6h # default is 2x timebucket, 2h
}
```

The drawback is that it could miss events because it doesn't look for previous events when it sees the first for a new persistenceId. I think think that was a protection mechanism for that it isn't guaranteed to see separate writes in the order they were written, i.e. a later event could be seen before and earlier event. With a decent eventual consistency delay that seems very unlikely, though.

**Comment by patriknw** [comment]
@chbatey Do you think we even need the `new-persistence-id-scan-timeout` if the eventual-consistency-delay is > seconds? Would that be when two subsequent events land on different partitions? (I remember you saw that inconsistency when stressing things, but was that taking eventual-consistency-delay into account?

**Comment by chbatey** [comment]
I think it is safe to set it to 0 with a decent eventual consistency delay. This was for a very rare edge case under stress with low eventual consistency delays.

**Comment by patriknw** [comment]
ok, I'll change the default

**Comment by chbatey** [comment]
+1 we've typically used the safest values for defaults but this one
introduces too much overhead

**Comment by beikern** [comment]
Hi @chbatey, 

Just a little question: when you said that this value will be safe to use with a 0 value using a decent consistency delay... that applies to a "low latency" consistency delay of 250 ms?

We are using the recommended low latency configuration from here: https://doc.akka.io/docs/akka-persistence-cassandra/current/events-by-tag.html#tuning-for-lower-latency just changing the eventual-consistency-delay from 50 ms to 250 ms.

**Comment by chbatey** [comment]
If you're using the lower latency settings then I don't think it is safe to
set this value to 0
