### ISSUE TITLE
Akka Persistence Cassandra - tag_writes buffer not batching correctly

### ISSUE THREAD

**Issue by agapic** [akka/akka-persistence-cassandra#856]
## Versions Used

akka-persistence-cassandra: v1.0.1
akka: v2.6.6
akka-projection: v0.2

## Details

Relevant resources: https://discuss.lightbend.com/t/akka-persistence-cassandra-unrecoverable-failures-tag-writes-buffer-grows-unboundedly/7643

The summary here is:
* We use CosmosDB with the Datastax Cassandra Driver in Java
* DB gets overloaded
* We have a max-messages-batch-size of 100 for `persistence.cassandra.events-by-tag`
* tag_writes buffer continues to increase (past the limit) and then tries to write very large batches to our DB
* Our DB rejects all writes with more than 100 events
* the buffer size never decreases, so we fail forever

## Expected Behaviour

I would expect the writes to be batched correctly based on the max-message-batch-size (100)

## Actual Behaviour

The buffer size keeps growing unboundedly because our DB rejects batch sizes > 100.

## Relevant logs

Logs here: https://discuss.lightbend.com/t/akka-persistence-cassandra-unrecoverable-failures-tag-writes-buffer-grows-unboundedly/7643

**Comment by chbatey** [comment]
This is fixed in the latest version but I understand you may want to disable synchronous writes to the tag views which will be a different issue.
