### ISSUE TITLE
Tag writer warning when event sourced actor restarts

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-cassandra#861]
Reported through the forums: https://discuss.lightbend.com/t/recommended-way-to-model-a-long-living-worker/7690

Looks as though an event sourced actor crashing and restarting through supervision could be leading to a warning from the tag writer, some logic triggered on restart that is only supposed to happen on stop-start?

Warning:
> Persistent actor starting for pid [pid]. Old ref hasn’t terminated yet: [Actor[akka://root/system/sharding/type/id/actor#-1167587395]]. Persistent Actors with the same PersistenceId should not run concurrently

**Comment by chbatey** [comment]
Ah so in this case there will be no `Terminated` and the persistent actor recovery will be the same ref as the previous one.

In that case we should check the ref and only log if it is different.

The warning doesn't stop the new actor from running so it is only an annoying log messages right now.
