### ISSUE TITLE
Improve events-by-tag performance on nearly empty databases

### ISSUE THREAD

**Issue by timon-k** [akka/akka-persistence-cassandra#867]
### Short description

Currently it takes surprisingly long (3 minutes) to run events-by-tag queries on databases which are completely or almost empty.

As a user, I would expect queries on empty databases to complete within some seconds at maximum. Especially in short integration test sequences I do not want to wait multiple minutes until my test system is useable.

### Details

I have attached [an example](https://github.com/akka/akka-persistence-cassandra/files/6006205/querydemo.zip) which creates a `PersistentDummyEntity` (persistent actor which does nothing expect tagging every event with an `exampleTag`) and creates a single event for this dummy actor.

This single event is then retrieved using the events-by-tag query once using the standard query starting at `Offset.noOffset` and once using a query which determines a better starting offset first ("quickstart offset").

```scala
object Main extends App {
  import PersistentDummyEntity._

  implicit val system: ActorSystem[Command] =
    ActorSystem(PersistentDummyEntity("dummy"), "dummy")
  implicit val ec: ExecutionContext = system.executionContext

  system ! DoNothing()  // Create one single event

  val readJournal =
    PersistenceQuery(system).readJournalFor[CassandraReadJournal](CassandraReadJournal.Identifier)

  readJournal
    .eventsByTag(exampleTag, Offset.noOffset)
    .runForeach(envelope =>
      system.log.info(
        s"Standard query: Received event ${envelope.sequenceNr} for ${envelope.persistenceId}",
      ),
    )

  quickstartOffset(exampleTag).foreach(startOffset =>
    readJournal
      .eventsByTag(exampleTag, startOffset)
      .runForeach(envelope =>
        system.log.info(
          s"Quickstart query: Received event ${envelope.sequenceNr} for ${envelope.persistenceId}",
        ),
      ),
  )
}
```

This is what the `quickstartOffset` does, it basically tries to determine the timestamp of the first correctly-tagged event in the database:

```scala
  def quickstartOffset(targetTag: String)(implicit ec: ExecutionContext) = {
    val session = CassandraSessionRegistry(system).sessionFor("akka.persistence.cassandra")
    val tagTable = {
      val cassandraConfig = system.settings.config.getConfig("akka.persistence.cassandra")
      val keyspace = cassandraConfig.getString("journal.keyspace")
      val table = cassandraConfig.getString("events-by-tag.table")
      s"$keyspace.$table"
    }
    val query = s"select min(timestamp) from $tagTable where tag_name = ? allow filtering"

    session.selectOne(query, targetTag).flatMap {
      case Some(row) if row.getUuid(0) != null =>
        // Previous entries exist => start at their offset
        Future.successful(TimeBasedUUID(row.getUuid(0)))
      case _ =>
        // No previous entries exist => start at the current time minus a safety margin
        val skipThePastOffset =
          readJournal.timeBasedUUIDFrom(System.currentTimeMillis() - 1.minute.toSeconds)
        Future.successful(skipThePastOffset)
    }
  }
```

The full code is in the [attached zip file](https://github.com/akka/akka-persistence-cassandra/files/6006205/querydemo.zip). If you

1. start cassandra: `docker run --rm -d -p 127.0.0.1:9042:9042/tcp cassandra`
2. run the example: `sbt run`

an example log output is

```shell
[info] running (fork) querydemo.Main
22:44:24.648 [main] INFO  com.datastax.oss.driver.internal.core.DefaultMavenCoordinates - DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core) version 4.9.0
22:44:27.080 [s0-admin-0] INFO  com.datastax.oss.driver.internal.core.time.Clock - Using native clock for microsecond precision
22:44:37.693 [dummy-akka.actor.default-dispatcher-6] INFO  akka.persistence.cassandra.query.EventsByTagStage - [74e83608-78af-4727-8ad6-7dd83e303b47]: EventsByTag query [exampleTag] starting with EC delay 2000ms: fromOffset [7f057f10-7232-11eb-8080-808080808080 (2021-02-18 21:44:36:993)] toOffset [None]
22:44:40.748 [dummy-akka.actor.default-dispatcher-7] INFO  akka.actor.typed.ActorSystem - Quickstart query: Received event 1 for dummy
22:44:43.139 [dummy-akka.actor.default-dispatcher-4] INFO  com.datastax.oss.driver.api.core.uuid.Uuids - PID obtained through native call to getpid(): 4728
22:44:43.139 [dummy-akka.actor.default-dispatcher-14] INFO  akka.persistence.cassandra.query.EventsByTagStage - [56717f3f-bc30-41b3-a7d3-9bb5a3ace842]: EventsByTag query [exampleTag] starting with EC delay 2000ms: fromOffset [a4698000-8f19-11e5-8080-808080808080 (2015-11-20 00:00:00:000)] toOffset [None]
22:47:24.897 [dummy-akka.actor.default-dispatcher-17] INFO  akka.actor.typed.ActorSystem - Standard query: Received event 1 for dummy
```

So it took approximately 3 seconds here to receive the one and only stored event using the "quickstart approach" whereas it took almost 3 minutes to query the same event using the default events-by-tag query. When the loglevel is increased `DEBUG` it becomes evident that the second query (starting at offset `2015-11-20 00:00:00:000`) scans through all of the time windows from 2015 to 2021 and needs 3 minutes for that.

Would it make sense to 
* make this kind of quickstart behavior the default for `Offset.none` or 
* provide an optional helper function which can supply such a quickstart offset as part of the standard `akka-persistence-cassandra` package?

Or am I missing something here and there is a trivial way to boost the performance of the setup without any custom start offset?

I am aware that my solution may have some drawbacks since it is based on the query `select min(timestamp) from $tagTable where tag_name = ? allow filtering`, so it might be slow for larger data volumes where the `allow filtering` becomes expensive. I did not test that. But I only use this as part of a projection (as a custom `SourceProvider`) to determine the initial projection offset. So the query is actually only executed once at the start of the projection.

**Comment by beikern** [comment]
Check this issue: https://github.com/akka/akka-persistence-cassandra/issues/821

I believe that your issue is caused by the default `akka.persistence.cassandra.events-by-tag.first-time-bucket` value, which is set to long time ago (2015).

`akka.persistence.cassandra.events-by-tag.first-time-bucket="20151120T00:00" `

If I'm not wrong, if you use the `Offset.none` syntax queries will start from `first-time-bucket` taking way more time than starting from a custom offset or from a nearly first-time-bucket.

Try to set `akka.persistence.cassandra.events-by-tag.first-time-bucket" ` to something like yesterday or something like that, it may improve the times.

**Comment by timon-k** [comment]
Thank you for the quick response! Indeed, setting the `first-time-bucket` to something like beginning of 2021 improves the performance a lot. With this addition it takes 5s to discover the first event, compared to 3s when using the adaptive start offset code shown above.

To be honest, I still not super-happy with setting the `first-time-bucket` manually. The akka persistence query docs state the following in `akka/persistence/query/Offset.scala`:

```scala
/**
 * Used when retrieving all events.
 */
case object NoOffset extends Offset {
  ...
}
```

So as a user, I would expect the `NoOffset` setting to return all existing entries for the given tag. The current implementation of the query in `akka-persistence-cassandra` will only return the events after this `first-time-bucket`. That means, that even though you specified `NoOffset`, you still have an implicit offset in your query. So the user runs into the danger of setting `first-time-bucket` as too early (degenerates performance) or too late (skips events), where he actually simply wanted all events.

Wouldn't it be worth to adopt behavior as defined above (start at first existing event _or_ at some safety margin before _now_ if there are no events) in order to come close to the intention of `NoOffset`?

**Comment by patriknw** [comment]
> start at first existing event or at some safety margin before now if there are no events

The tagged events are stored in time buckets as partition. It can't know where the first event is stored so it must scan all buckets from a starting point if an offset is not given.

You have two options. The config or defining an fictive offset. The offset can be constructed from a timestamp so you can define that now minus safetey margin yourself.

**Comment by timon-k** [comment]
While I do understand that the events are stored in time buckets, I do not see why `akka-persistence-cassandra` needs to use a _static_ starting point if an offset is not given.

The starting point could be determined dynamically (as shown above) from the existing data.

Advertising in the documentation that people have to set this starting point manually as done in #821 will very likely improve the user experience for developers who want to try out the events-by-tag query. But even the developers will be annoyed that they have to maintain this starting offset in their integration test configs (or the tests will become slower over time).

Operators who have to run systems based on `akka-persistence-cassandra` will likely be even less happy with having to maintain some manual starting offset, where, if they set it wrong, their system will become slow (too far in the past) or behave incorrect (too far in the future).

To me, the complexity of this config destroys part of the "it just works" experience, so if there is an easy way to improve it, then I think it should be done. I'd also be willing to contribute work on the topic.

**Comment by chbatey** [comment]
Hi @timon-k this query `select min(timestamp) from $tagTable where tag_name = ? allow filtering` will timeout, or OOM one of your Cassandra nodes, as soon as there is a large amount of data. It is a full table scan.
A scalable solution would need to store the first timestamp for each tag in another table that is partitioned such that the events by tag query can access it on O(1). That table would need to be backfilled from existing data before enabling the feature.  

The most common use case for events by tag is to have a small number of tags and read and store the offset you're up to so this penality of a slow query or having to set the first-time-bucket is very minimal.

If using arbitrary tags and a lots of separate queries without storing an offset I can see why this would be a lot worse. 

I think we'd be happy to accept a contribution here but it isn't something we plan to work on as nearly all our users are following the above scenario as the query is used to implement CQRS.

**Comment by an-tex** [comment]
Could the new `akka_projection.projection_management` table or something similar be used to retrieve the oldest tag in a more efficient way?

**Comment by timon-k** [comment]
No, for two reasons. On the one hand, `akka-persistence-cassandra` should probably not depend on `akka-projections`.

On the other hand, even if you have the projection data, it does not help you in the first persistence query of a new projection (which is the case we are interested in here). If you have an existing projection everything works fine (start at stored offset), if you don't then you are back at scanning the events starting from the global start offset.

Honestly, I did not find the time to actually work on this, yet. After understanding the complexities (and potential bugs) of storing the start offset per tag, the current config-based approach does not look so bad any longer.
