### ISSUE TITLE
PersistentShardCoordinator recover issue with Casssandra 2.2.4

### ISSUE THREAD

**Issue by atamborrino** [akka/akka-persistence-cassandra#95]
Hello,

I am experiencing an issue with Akka Sharding 2.4.4 backed by Akka Persistence Cassandra 0.14  with Cassandra 2.2.4.

My config is the following:
```
akka {
  cluster {
    metrics.enabled = off

    sharding {
      remember-entities = on
      journal-plugin-id = cassandra-journal-akka-sharding
      snapshot-plugin-id = cassandra-snapshot-store-akka-sharding
    }

  }
}

cassandra-journal-akka-sharding = ${cassandra-journal} {
  cassandra-2x-compat = on
  keyspace = "akka_sharding"
}
cassandra-snapshot-store-akka-sharding = ${cassandra-snapshot-store} {
  keyspace = "akka_sharding_snapshot"
}
```

The first time I run my node, the keyspace and tables are created fine and the system is running (events are put in akka_sharding.messages). 
However, when I stopped and restarted my node, akka.cluster.sharding.PersistentShardCoordinator failed with the following error:
```
2016-05-10 11:48:29,201 [warn] - akka.persistence.cassandra.query.scaladsl.CassandraReadJournal - Failed to connect to Cassandra and initialize. It will be retried on demand. Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 2:13 no viable alternative at input 'MATERIALIZED' (      [CREATE] MATERIALIZED...)
2016-05-10 11:48:29,213 [error] - akka.cluster.sharding.PersistentShardCoordinator - Persistence failure when replaying events for persistenceId [/sharding/TaskManagerCoordinator]. Last known sequence number [0]
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.SyntaxError: line 2:13 no viable alternative at input 'MATERIALIZED' (      [CREATE] MATERIALIZED...)
```

I know that ```cassandra-2x-compat = on``` is taken into account because when I remove this line, the system fails **during the first start** when creating the keyspace with the error:
```
2016-05-10 11:45:29,939 [error] - akka.cluster.sharding.PersistentShardCoordinator - Persistence failure when replaying events for persistenceId [/sharding/TaskManagerCoordinator]. Last known sequence number [0]
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.SyntaxError: line 2:13 no viable alternative at input 'MATERIALIZED' (      [CREATE] MATERIALIZED...)
```

It seems that when they are events in ```cassandra-journal-akka-sharding```, the PersistentShardCoordinator fails to recover even with cassandra-2x-compat = on

**Comment by patriknw** [comment]
The config relation between the write and the query parts are a bit messy at the moment. We will improve that in https://github.com/akka/akka-persistence-cassandra/issues/81

What you have missed is to configure the relation between the `query-plugin` and the `write-plugin`. It should be:

```
cassandra-journal-akka-sharding = ${cassandra-journal} {
  cassandra-2x-compat = on
  keyspace = "akka_sharding"
  query-plugin = "cassandra-query-journal-akka-sharding"
}

cassandra-query-journal-akka-sharding = ${cassandra-query-journal} {
  write-plugin = "cassandra-journal-akka-sharding"
}
```

Let me know if that helps.

**Comment by atamborrino** [comment]
Thanks for your quick response, the issue is gone!

**Comment by patriknw** [comment]
You're welcome.
Yeah that config must be improved.
