### ISSUE TITLE
persistAll doesn't batch messages when payload size > max-message-batch-size

### ISSUE THREAD

**Issue by lakhak** [akka/akka-persistence-cassandra#954]
### Versions used 

Akka version: 2.6.9
Akka Persistence Cassandra: 1.0.5

### Expected Behavior

Our use-case is to use Akka Persistence with AWS Keyspaces, which only supports 30 commands in a batch: https://docs.aws.amazon.com/keyspaces/latest/devguide/functional-differences.html#functional-differences.batch.

When configuring `max-message-batch-size = 30` the expected behaviour is that when attempting to persist more than 30 messages with persistAll, messages should be grouped into unlogged batches of 30 statements.

Also in akka.persistence.cassandra.journal.PersistAllSpec, `max-message-batch-size = 100` and 200 messages are persisted as part of the test. Expected behaviour is that the driver should execute this as two batches of 100.

### Actual Behavior

Fails when trying to persist the events to AWS Keyspaces.

Also when running PersistAllSpec the test passes but appears to execute a single batch of 200.

### Relevant logs

When configured to use AWS Keyspaces, the persistent actor logs the exception:

`com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Batches with more than 30 statements are not supported.`

### Reproducible Test Case

Please provide a PR with a failing test.

If the issue is more complex or requires configuration, please provide a link to a project that reproduces the issue.

**Comment by patriknw** [comment]
The semantics of PersistAll is that it should store the events atomically (all or nothing). That would not be possible if we would split up in several batches. I think you have to handle this in the application layer, in the actor, grouping the events there and persist events of 30.

**Comment by lakhak** [comment]
Thanks for the explanation, makes sense. This is indeed the what we have done so I'll go ahead and close this ticket.
