### ISSUE TITLE
Serialise PersistentRepr as Json

### ISSUE THREAD

**Issue by t3hnar** [akka/akka-persistence-cassandra#97]
I'd like to serialiser `PersistentRepr` as `Json`, however it looks like I would need to heavily override `CassandraJournal` in order achieve this.

1. Do you have any plans on providing ability to serialise `PersistentRepr` as `Json` ?
2. Are there any ideas on how it can be done on my side with minimal changes to `CassandraJournal` ?

**Comment by patriknw** [comment]
`PersistentRepr` is not serialized and stored at all, any longer. Your event data is stored in a separate column using your serializer. See https://github.com/akka/akka-persistence-cassandra/pull/21

Does that solve the problem?

**Comment by patriknw** [comment]
by the way, here is a Json serializer: https://github.com/lagom/lagom/blob/master/jackson/src/main/scala/com/lightbend/lagom/internal/jackson/JacksonJsonSerializer.scala

**Comment by t3hnar** [comment]
thx @patriknw will take a look and most probably close the issue, but a bit later.

**Comment by patriknw** [comment]
ok, thanks

**Comment by t3hnar** [comment]
@patriknw It would be ideally to serialise `PersistentRepr` as JSON equally in different storages including Cassandra, but looks like I'll end up binding json serialisers to events for persistence and kryo serialiser for network communication
Thanks.
